### ISSUE TITLE
Add an equivalent to zlib's compressBound/deflateBound

### ISSUE THREAD

**Issue by jrmuizel** [ebiggers/libdeflate#1]
I was looking at implementing a squash plugin for libdeflate and it would be handy to have this functionality. I expect this would be very useful for other users of this library as well.

**Comment by ebiggers** [comment]
Thanks; I'll look into it.  In my experience, a common pattern with chunk-based compression is that you try to compress `n` bytes to `n - 1` bytes, and if it fails, you store the chunk uncompressed.  With that pattern, there's no need for a `deflateBound()`.  But it's probably nice to have.

**Comment by nemequ** [comment]
That's a fairly common pattern, but definitely not universal.  Sometimes you don't have the option of storing content uncompressed; if it's a very rare occurrence it's cheaper to avoid the having to signal whether each block is compressed or not and just take the occasional hit.

Interestingly, there are codecs in Squash which will simply refuse to attempt to compress if you don't feed it whatever it's bound function suggests… libbsc does that, and I noticed at least one other codec recently which does it (can't remember which one, though).

Anyways, like you said, nice to have.

**Comment by ebiggers** [comment]
deflate_compress_bound(), zlib_compress_bound(), and gzip_compress_bound() functions have been added.  They may overestimate the required size by a lot, but they are a starting point.
