### ISSUE TITLE
libdeflate_zlib_compress returns 0 if out_nbytes_avail is the exact size of the compressed output

### ISSUE THREAD

**Issue by cgohlke** [ebiggers/libdeflate#102]
Hello,

I added a deflate codec based on the libdeflate library to the Python imagecodecs package and found that some tests are failing. Using libdeflate 1.6 compiled with Visual Studio 2017 on Windows 10, 64-bit.

The issue is that `libdeflate_zlib_compress` returns `0` if the length of the `out` buffer is exactly the size of the compressed input. The following minimal standalone C program fails, i.e. exits with code 7. It looks like the output buffer needs to be at least 9 bytes longer than the compressed output. Is this expected?
```C
/* libdeflate_test.c */

#include <stdlib.h>
#include <libdeflate.h>

int main()
{
    const char *in = "1234567890";
    char *out = NULL;
    size_t in_nbytes = 10;
    size_t out_nbytes_avail;
    size_t result;
    struct libdeflate_compressor *compressor = NULL;

    compressor = libdeflate_alloc_compressor(6);
    if (compressor == NULL) return 1;

    /* using libdeflate_zlib_compress_bound succeeds */
    out_nbytes_avail = libdeflate_zlib_compress_bound(compressor, in_nbytes);
    out = malloc(out_nbytes_avail);
    if (out == NULL) return 2;
    result = libdeflate_zlib_compress(compressor, (const void *)in, in_nbytes, (void *)out, out_nbytes_avail);
    free(out);
    if (result == 0) return 3;

    out_nbytes_avail = result;  /* the size of the compressed output */
        
    /* using out_nbytes + 9 succeeds */
    out = malloc(out_nbytes_avail + 9);
    if (out == NULL) return 4;
    result = libdeflate_zlib_compress(compressor, (const void *)in, in_nbytes, (void *)out, out_nbytes_avail + 9);
    free(out);
    if ((result == 0) || (result != out_nbytes_avail)) return 5;

    /* using out_nbytes fails */
    out = malloc(out_nbytes_avail);
    if (out == NULL) return 6;
    result = libdeflate_zlib_compress(compressor, (const void *)in, in_nbytes, (void *)out, out_nbytes_avail);
    free(out);
    if (result == 0) return 7;

    libdeflate_free_compressor(compressor);

    return 0;
}
```

**Comment by ebiggers** [comment]
> Is this expected?

Pretty much.  It's tricky to handle writing to the last few bytes, so libdeflate doesn't try.  So if some data compresses to `n` bytes, and then you re-try the compression (with the same level and some version of libdeflate), slightly more than `n` bytes of space may still be needed in the output buffer, even though the compressed size will still end up being `n`.  I can see why this would be unexpected, but I also didn't expect this to matter for anyone.  The `*_compress_bound()` functions always return enough space.  And also, if data has been compressed, there shouldn't be any reason to try to compress it again while also intentionally using the exact same settings, *and* happening to use a minimum-sized output buffer.  Can you explain why this case matters for you?  It would be possible to change this, but I expect it would have a measurable impact on compression performance.

**Comment by cgohlke** [comment]
Thank you for the answer! You are right, it does not really matter. It was just unexpected and I wanted to check. The imagecodecs tests check this case for a dozen different compression libraries, and only three libraries can't encode to a buffer of exact size (at least for the sizes tested): liblzf needs one additional byte, zstandard needs a minimum of 64 bytes, and libdeflate needs 9 additional bytes. But there is no real world case where I rely on this.

**Comment by jberryman** [comment]
>  can see why this would be unexpected, but I also didn't expect this to matter for anyone.

It's fine to me, and not unexpected but it would be nice to have a note in `libdeflate.h`. As someone not very comfortable with C and writing bindings for libdeflate, I suspected I might have done something wrong.

Also it would be nice to have some heuristic if possible;  For instance maybe I'm okay bypassing compression if we can't get the compression ratio past 0.5 . What size output buffer should I pass? From playing with it a little bit it seems like there are usually 8 bytes of slop or so, so I’d pass `0.5*input_size + 8`

**Comment by ebiggers** [comment]
I decided to fix this in https://github.com/ebiggers/libdeflate/commit/b8f2e78bdd76562850894226c26c324f698c3958.
