### ISSUE TITLE
File decompressed correctly, but libdeflate returns a LIBDEFLATE_BAD_DATA status

### ISSUE THREAD

**Issue by GWRomeyRomes** [ebiggers/libdeflate#106]
I am having an issue with the attached file where it seems to decompress correctly, but the libdeflate library returns a LIBDEFLATE_BAD_DATA status. I have used the following Python script to check whether decompression works and it does not produce any errors:

```python
import os
import zlib

input_file = open('Test.bin', 'rb')
input_data = input_file.read()
zlib_obj = zlib.decompressobj()
decompressed = zlib_obj.decompress(input_data)
output_file = open('Decompressed.bin', 'wb')
output_file.write(decompressed)
output_file.close()
input_file.close()
```

The test file can be found within the attached archive: [Test.zip](https://github.com/ebiggers/libdeflate/files/5568171/Test.zip)

Not sure whether this is needed, but here is the code used to reproduce the issue:

```c++
#include <iostream>
#include <fstream>
#include <vector>
#include <stdint.h>
#include <memory>
#include "libdeflate.h"

using namespace std;

int main()
{
    ifstream inputFile("Test.bin", ifstream::binary | ifstream::in);

    inputFile.seekg(0, ifstream::end);
    size_t inputFileSize = inputFile.tellg();
    inputFile.seekg(0, ifstream::beg);

    vector<uint8_t> inputData(inputFileSize);
    vector<uint8_t> decompressedData(10240, 0);

    inputFile.read(reinterpret_cast<char*>(inputData.data()), inputFileSize);

    auto decompressor = std::unique_ptr<libdeflate_decompressor, std::function<void(libdeflate_decompressor*)>> (libdeflate_alloc_decompressor(), libdeflate_free_decompressor);
    size_t decompressedSize = 0;
    libdeflate_result decompressedResult = libdeflate_zlib_decompress(decompressor.get(), inputData.data(), inputData.size(), decompressedData.data(), decompressedData.size(), &decompressedSize);

    if (decompressedResult == LIBDEFLATE_SUCCESS)
        cout << "Success" << endl;
    else
        cout << "Fail" << endl;

    return 0;
}
```

OS: Centos 7
Compiler: GCC 4.8.5

Any help is much appreciated.

**Comment by ebiggers** [comment]
Your file doesn't contain a full DEFLATE stream.  It has only one compressed block, which does *not* have the "final block" flag set, so there should be more block(s) following it, but the buffer ends at that point.  So it's expected that decompression fails.

On failure, the output buffer may contain what has been decompressed so far, but that's an implementation detail that must not be relied on.

**Comment by GWRomeyRomes** [comment]
So how can this issue be overcome as the data comes from a third party? Also is this a case where libdeflate is more strict in how it decompresses data compared to zlib?

**Comment by ebiggers** [comment]
zlib has a streaming API, so it supports compressing/decompressing partial streams.  libdeflate doesn't; it only supports full streams.

**Comment by GWRomeyRomes** [comment]
That's fair enough. Thank you for your help. I will just have to use zlib for decompression then.
