### ISSUE TITLE
Custom mem* funcs conflict with Rust builtins in freestanding mode

### ISSUE THREAD

**Issue by RReverser** [ebiggers/libdeflate#107]
Now that all the PRs have been merged in various repos, I had a chance to try out the freestanding mode in Rust + Wasm, and looks like there are some errors during the final link:

```
  = note: rust-lld: error: duplicate symbol: memcpy
          >>> defined in /tmp/rustc8Dk9RS/liblibdeflate_sys-af8dc65af1faa178.rlib(utils.o)   
          >>> defined in /src/target/wasm32-unknown-unknown/release/deps/libcompiler_builtins-d2eefcac0e362d46.rlib(compiler_builtins-d2eefcac0e362d46.compiler_builtins.b387rgbk-cgu.6.rcgu.o)

          rust-lld: error: duplicate symbol: memmove
          >>> defined in /tmp/rustc8Dk9RS/liblibdeflate_sys-af8dc65af1faa178.rlib(utils.o)   
          >>> defined in /src/target/wasm32-unknown-unknown/release/deps/libcompiler_builtins-d2eefcac0e362d46.rlib(compiler_builtins-d2eefcac0e362d46.compiler_builtins.b387rgbk-cgu.6.rcgu.o)

          rust-lld: error: duplicate symbol: memset
          >>> defined in /tmp/rustc8Dk9RS/liblibdeflate_sys-af8dc65af1faa178.rlib(utils.o)   
          >>> defined in /src/target/wasm32-unknown-unknown/release/deps/libcompiler_builtins-d2eefcac0e362d46.rlib(compiler_builtins-d2eefcac0e362d46.compiler_builtins.b387rgbk-cgu.6.rcgu.o)

          rust-lld: error: duplicate symbol: memcmp
          >>> defined in /tmp/rustc8Dk9RS/liblibdeflate_sys-af8dc65af1faa178.rlib(utils.o)   
          >>> defined in /src/target/wasm32-unknown-unknown/release/deps/libcompiler_builtins-d2eefcac0e362d46.rlib(compiler_builtins-d2eefcac0e362d46.compiler_builtins.b387rgbk-cgu.6.rcgu.o)


error: aborting due to previous error
```

It appears that Rust has its own versions of those functions as compiler-builtins intrinsics, and they conflict with those defined in https://github.com/ebiggers/libdeflate/blob/master/lib/utils.c during the link.

Is it possible to limit the visibility of those functions or define them with `libdeflate_` prefix instead? Or is it something that the Rust wrapper (libdeflater) should handle? (cc @adamkewley who might also be interested and have thoughts)

**Comment by RReverser** [comment]
Actually, it's interesting, it happens only when `-Z build-std=...` is used (for Wasm threads) but not with normal Rust... @alexcrichton does Rust have different visibility for intrinsics when `build-std` feature is used?

**Comment by ebiggers** [comment]
By definition a freestanding environment doesn't have these functions available.  But the compiler can emit calls to them.  That's why when libdeflate is built in freestanding mode, it has to define them.

It seems that a freestanding build isn't actually what you're looking for.

**Comment by RReverser** [comment]
> It seems that a freestanding build isn't actually what you're looking for.

No, it's definitely freestanding; the problem is that those functions are "shimmed" in global scope by both libdeflate and Rust in this case - even though / because they're not provided by libc.

**Comment by RReverser** [comment]
It's like, forgetting Rust aside, imagine if there was 2nd library that was also being built in freestanding mode.

Now, libc doesn't provide those functions, so both libdeflate and this 2nd library work around this fact by using custom functions `memset`, `memcpy` and so on. Since all of those functions are common names and end up in the global scope, this inevitably leads to a linker conflict.

**Comment by ebiggers** [comment]
Can you check if making these weak symbols fixes this?  https://github.com/ebiggers/libdeflate/pull/108

**Comment by RReverser** [comment]
Thanks for the fix! I'll be able to check on Monday.

**Comment by alexcrichton** [comment]
There shouldn't be any differences in `-Zbuild-std` visibility, but it may be that things are built just differently to cause issues.

**Comment by RReverser** [comment]
> There shouldn't be any differences in `-Zbuild-std` visibility, but it may be that things are built just differently to cause issues.

I see. It does seem odd that it doesn't happen in non-build-std builds. I thought the cause might be that compiler-builtins intrinsics get completely internalised in "proper" Rust builds, but have to be linked against statically in `build-std` mode.

**Comment by RReverser** [comment]
@ebiggers Thanks, just tried and that does fix the issue and both variants of builds succeed (one where there is no compiler-builtins to link against, and another where there is).

**Comment by ebiggers** [comment]
> @ebiggers Thanks, just tried and that does fix the issue and both variants of builds succeed (one where there is no compiler-builtins to link against, and another where there is).

Thanks, merged now.
