### ISSUE TITLE
#include protector in lib/cpu_features_common.h

### ISSUE THREAD

**Issue by benkasminbullock** [ebiggers/libdeflate#117]
`lib/cpu_features_common.h` doesn't have a "double include" guard like the other header files so it can be included twice, creating errors.

**Comment by ebiggers** [comment]
`lib/cpu_features_common.h` is an internal library header.  You're not including it in an application using libdeflate, right?  It's never included twice, so it's not possible that you would be seeing a build error unless you made changes to libdeflate, or are including internal library headers in an application (which is not supported at all).

Also, several of the internal library headers don't have include guards.  Is there a reason you're calling attention to this particular one?

**Comment by benkasminbullock** [comment]
I might have got this wrong but you seem to be using the struct cpu_feature in the library which is defined in that header.

**Comment by ebiggers** [comment]
The header is used only in the library itself (and not in a way that it *needs* an include guard), not outside it.  It would be good to add an include guard, but I wanted to understand why you were calling attention to this specifically.

**Comment by benkasminbullock** [comment]
I don't need you to take any action here, I just pointed it out in case you had forgotten to add it. Thank you.
