### ISSUE TITLE
Macros rather than magic numbers?

### ISSUE THREAD

**Issue by benkasminbullock** [ebiggers/libdeflate#118]
Does libdeflate provide macros for things like the default, maximum and minimum compression levels? I couldn't see them in libdeflate.h. I think it's better to have a macro like

    #define LIBDEFLATE_DEFAULT_COMPRESSION 6

rather than using "magic numbers".

**Comment by ebiggers** [comment]
No, not currently.  I'm actually not certain that this would be a good idea.  For one, there is no default compression level; it's up to the application using libdeflate.  The minimum could also be either 0 or 1; it depends on whether 0 is counted or not.  The maximum is currently 12, but even higher levels could be supported in the future.  Having a constant defined to 12 might imply that higher levels will never be supported and make users to start depending on the maximum being exactly 12.

**Comment by benkasminbullock** [comment]
> Having a constant defined to 12 might imply that higher levels will never be supported and make users to start depending on the maximum being exactly 12.

It seems exactly the opposite to me, at the moment I have to hardwire 12 and 6 into my code to say to the user "sorry, over the maximum". If you define a macro then you can change the maximum to 20 or 1000 or something without having to change lots of magic numbers in code.

**Comment by ebiggers** [comment]
It's not really about minimum/maximum, but rather about the performance and compression ratio tradeoff of a particular level.  I'm concerned that people could rely on LIBDEFLATE_BEST_COMPRESSION making a particular tradeoff.  People could also assume that it makes the same tradeoff as zlib's ZLIB_BEST_COMPRESSION (level 9).

Then if I add level 20 that is 100x slower, that breaks that assumption.

Making people explicitly choose the compression level they want avoids that issue.

Another thing to keep in mind is that if your application dynamically links to libdeflate, and libdeflate is updated, the library could potentially support more compression levels than your application knew about when it was being compiled.  Macros in APIs to give the maximum value of something are never a good idea for this reason; it's much better to dynamically discover the maximum.  (This can currently be done by calling `libdeflate_alloc_compression()` with higher levels until it fails, though adding a function that returns the maximum would be a better approach.  I'm open to doing that, but it would have to be documented  carefully, as per the concerns above.)

**Comment by benkasminbullock** [comment]
OK, I'll just document what you have described above in my documentation. Thank you.
