### ISSUE TITLE
Benchmark numbers against zlib

### ISSUE THREAD

**Issue by alexhultman** [ebiggers/libdeflate#120]
Hello,

I've compiled your benchmark program with -flto -O3 and for a 1MB file I cannot see any significant gains over zlib.

I see small gains, very insignificant, but both take roughly 16ms to finish. Is there some way I can run the benchmark many times over a period of 10 seconds to get a more accurate number?

My use case would be DEFLATE compression with non-sliding-window and a size of about 1kb or so.

Would libdeflate excel here over zlib or should just just keep using zlib for this case?

**Comment by alexhultman** [comment]
Am I misunderstanding the "zlib wrapper?". Is that using zlib, or is that wrapping libdeflate in the zlib interfaces? What am I testing when I pass -z? With a 300 MB file I still get pretty much identical numbers so this leads me to believe I am using your benchmark wrong? How can I test the same using zlib?

**Comment by alexhultman** [comment]
Oh wow, I am a total idiot. I'm supposed to pass -C libz!

With that I get about 2.3x performance with libdeflate compared to zlib so that's significant and I will make use of this library! Thanks

**Comment by alexhultman** [comment]
I'm trying to inflate a known message "Hello" using DEFLATE but it always fails - why doesn't this work? The 11 bytes are from an RFC that says it should inflate using the DEFLATE algorithm?

```
#include <stdio.h>
#include "libdeflate/libdeflate.h"

int main() {
    libdeflate_decompressor *decompressor = libdeflate_alloc_decompressor();

    size_t written = 0;
    unsigned char buf[512];

    // https://tools.ietf.org/html/rfc7692#section-7.2.3.1
    unsigned char in[11] = {
        0xf2, 0x48, 0xcd, 0xc9, 0xc9, 0x07, 0x00, 0x00, 0x00, 0xff, 0xff
    };

    libdeflate_result res = libdeflate_deflate_decompress(decompressor, in, 11, buf, 512, &written);

    // this fails with bad data
    printf("Result: %d, Written: %ld\n", res, written);
}

```

**Comment by ebiggers** [comment]
As you figured out, `benchmark -z` compresses the data in the zlib format instead of the DEFLATE format.  It doesn't change which library is used.  `-C libz` and `-D libz` select the zlib library (libz) for compression and decompression respectively.

The reason that the above 11-byte message doesn't decompress is that it isn't a complete DEFLATE stream; the last block doesn't have the BFINAL bit set.

**Comment by alexhultman** [comment]
Do you have any opinion regarding the section linked in https://tools.ietf.org/html/rfc7692#section-7.2.3.1 ?

How would one apply libdeflate to that use case?

**Comment by alexhultman** [comment]
With zlib there is Z_SYNC_FLUSH which "makes the above work". How would one go about doing the same with libdeflate?

```
7.3.  Implementation Notes

   On most common software development platforms, the DEFLATE
   compression library provides a method for aligning compressed data to
   byte boundaries using an empty DEFLATE block with no compression.
   For example, zlib [zlib] does this when "Z_SYNC_FLUSH" is passed to
   the deflate function.
```

**Comment by ebiggers** [comment]
Also:

> Is there some way I can run the benchmark many times over a period of 10 seconds to get a more accurate number?
> 
> My use case would be DEFLATE compression with non-sliding-window and a size of about 1kb or so

The `benchmark` program doesn't support running multiple iterations over each chunk, but you could choose the desired chunk size and pass it multiple chunks.  For example try `-s 1000` and a file of size at least 1 MB (but preferably more like 10 MB).

**Comment by ebiggers** [comment]
libdeflate isn't designed for streaming use cases.  So it doesn't support things like Z_SYNC_FLUSH.

**Comment by alexhultman** [comment]
If I do this:

    unsigned char in[11] = {
        0xf2|1, 0x48, 0xcd, 0xc9, 0xc9, 0x07, 0x00, 0x00, 0x00, 0xff, 0xff
    };

It decompresses to "Hello". Is this viable? Can I do something like that to ensure things will decompress? This is not about streaming, there is no sliding window. All compressions and decompressions are going to be without any sliding window at all.

**Comment by ebiggers** [comment]
The RFC that you linked to makes it sound like the sliding window is shared between messages, and messages are delimited by Z_SYNC_FLUSH.  So are you sure that in your case each message can be decompressed independently of the others?  Or are you defining a new protocol not necessarily compatible with that RFC (in which case, if you want each message to be decompressed independently, you could just make the compressor properly terminate each message)?

As far as "manually" setting BFINAL without cooperation from the compressor, that would be hard to do since it needs to be set in the header for the final block, not the first block.  (It doesn't matter in the example above, but in general there might be multiple compressed blocks, so if you blindly set BFINAL on the first one, the output will be truncated.)

**Comment by alexhultman** [comment]
Yeah I figured that out. I can decompress multiple blocks now "HelloHello". I can solve this by appending the minimal empty deflate block with BFINAL set - do you know what that is? So far I have a simple "a": 4b e4 02 00

Z_SYNC_FLUSH is not only for streams, it also kind of enforces an end (just as if you had a BFINAL set on last block - at least that is how I see it.

You can share a sliding window but I only plan to use libdeflate when not sharing a sliding window.

**Comment by alexhultman** [comment]
Oh I am stupid I can use libdeflate to determine that:
1
0
0
ff
ff

**Comment by alexhultman** [comment]
So basically I just append 0x01, 0x00, 0x00, 0xff, 0xff to whatever I need to decompress and it will work?

**Comment by ebiggers** [comment]
> So basically I just append 0x01, 0x00, 0x00, 0xff, 0xff to whatever I need to decompress and it will work?

That will work if the compressed data already ends with an uncompressed block, such as the empty block generated by Z_SYNC_FLUSH.

> Z_SYNC_FLUSH is not only for streams, it also kind of enforces an end (just as if you had a BFINAL set on last block - at least that is how I see it.

There's no need for Z_SYNC_FLUSH if the DEFLATE stream won't continue later.  If the stream won't continue, the compressor should just terminate the stream.  (Unless you are using an existing protocol that requires Z_SYNC_FLUSH in this weird way, which it seems might be the case?)

**Comment by alexhultman** [comment]
What I do to make it work with this permessage-deflate standard is that I append "\x00\x00\xff\xff\x01\x00\x00\xff\xff" to whatever I get and then it seems to work. I will run a beefy 500+ testcase on this in a while but it seems to work. It would be nice if I didn't have to append anything though?

I am going to try and see if I can make the compress end work as well and then run tests  and if I get good results this will be my new goto library for non-sliding cases. Thanks for info so far!

**Comment by alexhultman** [comment]
Yeah libdeflate is crazy fast. I get a boost from 120k messages/second to over 200k in a particular test. I just need to fix some issues and this will be an awesome addition!

**Comment by alexhultman** [comment]
The same applies to compression; I need to append "\x01\x00\x00\xff\xff\x00" to the compression output to make it work. I think they cover this in the following section:

```
7.2.3.4.  Using a DEFLATE Block with "BFINAL" Set to 1

   On platforms on which the flush method using an empty DEFLATE block
   with no compression is not available, implementors can choose to
   flush data using DEFLATE blocks with "BFINAL" set to 1.

       0xf3 0x48 0xcd 0xc9 0xc9 0x07 0x00 0x00

   This is the payload of a message containing "Hello" compressed using
   a DEFLATE block with "BFINAL" set to 1.  The first 7 octets
   constitute a DEFLATE block with "BFINAL" set to 1 and "BTYPE" set to
   01 containing "Hello".  The last 1 octet (0x00) contains the header
   bits with "BFINAL" set to 0 and "BTYPE" set to 00, and 5 padding bits
   of 0.  This octet is necessary to allow the payload to be
   decompressed in the same manner as messages flushed using DEFLATE
   blocks with "BFINAL" unset.
 ```

I have a working flow of compression and decompression so I will run a lot of tests now but really - have you considered supporting this SYNC-like behavior? So one don't have to append crap to the end?

**Comment by ebiggers** [comment]
As I explained, Z_SYNC_FLUSH only makes sense for streaming, not for cases where each message is compressed independently.

Generally, the individual parts of streaming support don't make sense without full streaming support, which is something I don't have time to support in libdeflate.

Also, according to what you just quoted, the protocol you're using is actually specifically designed to be usable by a compressor without Z_SYNC_FLUSH support, as the protocol supports BFINAL being set.  It does say that a byte has to be appended, but that's particular to that protocol, not part of the DEFLATE stream.

**Comment by alexhultman** [comment]
Yep. I managed to get it working with only 1 byte appended. I will stop spamming you now but I did a compression test with some JSON and got 259 bytes vs. 276 bytes so libdeflate is faster and has better compression ratios here.

Thanks for the help - the only downsite I have now is that I have to append 9 bytes before decompressing but that is not a big issue as I have padded buffers anyways. Great!

**Comment by alexhultman** [comment]
Thanks for the help but it looks like I didn't use my brain here - I tested with too short inputs so libdeflate never compressed 🤦 . With larger ones Zlib does a faster job, and since performance is a function of change since last compression you really lose a lot of performance by restarting compression from scratch every time (and compression ratio) :(

libdeflate is probably best for files where all data is given up front and there only is one single file and that file being quite big.
