### ISSUE TITLE
Please allow to use external libdeflate package

### ISSUE THREAD

**Issue by yurivict** [ebiggers/libdeflate#121]
These lines
```
# WITH_LIBDEFLATE=1 enables fast paths for SHARED_COMPRESSOR and inflation
ifeq ($(WITH_LIBDEFLATE),1)
        override CXXFLAGS += -I libdeflate -DUWS_USE_LIBDEFLATE
        override LDFLAGS += libdeflate/libdeflate.a
endif
```
require bundled ```libdeflate``` but ```libdeflate``` packages are available on many systems: https://repology.org/project/libdeflate/versions

**Comment by ebiggers** [comment]
This is an issue in a project using libdeflate, not in libdeflate itself.  Please file this issue with the correct project.

**Comment by yurivict** [comment]
Sorry, wrong project.
