### ISSUE TITLE
How can I make vips use this library?  

### ISSUE THREAD

**Issue by AndKe** [ebiggers/libdeflate#129]
I am recompressing lots of (realtime generated) SVG's to png.  resolution is only about 472x288, only 10 colors. using a RPI4 at 2Ghz.

A highly skilled vips developer wrote:
"libpng spends almost all of its time in deflate compression, so swapping libz out for something faster is an easy win. People usually suggest:"  (link to libdeflate)

libpng , libz is mentioned, .. swapping out libz for libdeflate..   does it mean to uninstall libz ? /just compile libdeflate ? - do I need to symlink it somewhere, or does vips need to be recompiled to use it ?

So I git cloned, make , and did make install..   and each svg still takes 190ms to recompress.
Please push me in the right direction to actually *use* this library

**Comment by cielavenir** [comment]
interesting, but

- What is the vips URL?
- libz and libdeflate has different API. Does vips support libdeflate's?

**Comment by ebiggers** [comment]
libdeflate doesn't provide libz API compatibility (as I don't have time/resources to support that, especially the streaming support), so it's not a drop-in replacement.  The code using libz would need to be updated to use libdeflate instead (or as an alternative).
