### ISSUE TITLE
decompress_result clash with xpack

### ISSUE THREAD

**Issue by jibsen** [ebiggers/libdeflate#14]
This is a minor issue, but I was trying to add libdeflate to lzbench, which already contains your xpack library. I ran into an issue with the `decompress_result` enum, which is the same in both. Since enum names and values are in the global namespace, I can't include both public headers at the same time.

**Comment by ebiggers** [comment]
Thanks for the report.  I'm thinking about just prefixing everything in the libdeflate API with "libdeflate_" (or "LIBDEFLATE_" for constants) to avoid problems like this once and for all...

**Comment by ebiggers** [comment]
Fixed on the master branch.  libdeflate now uses distinctive names in its API.  In the case of the enum specifically I chose `libdeflate_result`. I decided it was not necessary to distinguish it futher as `libdeflate_decompress_result`.

**Comment by jibsen** [comment]
Thanks!
