### ISSUE TITLE
pkgconfig support

### ISSUE THREAD

**Issue by dankamongmen** [ebiggers/libdeflate#140]
It would be great if libdeflate built and installed a pkg-config .pc support file. I'm happy to whip this up for you, assuming you're not opposed to the idea.

**Comment by ebiggers** [comment]
Yes, that would be fine, please feel free to open a pull request for this.

**Comment by dankamongmen** [comment]
awesome, expect one this week. thanks!

**Comment by dankamongmen** [comment]
alright, i've got something that works, but it requires GNU Make. is that ok with you? windows (where you have `Makefile.msc`) doesn't need pkg-config, and is unchanged. the only annoyance will come on FreeBSD, where the Port will need build-depend on gmake and invoke `gmake`. is that cool with you?

if it's not, i can probably put something together with sed, but i don't personally see much value in that.

**Comment by ebiggers** [comment]
It doesn't need to work with anything other than GNU Make, but I think it would be better to use a template file and `sed` anyway.  It's weird to have the file embedded within the Makefile.
