### ISSUE TITLE
add libdeflate to MacPorts

### ISSUE THREAD

**Issue by dankamongmen** [ebiggers/libdeflate#144]
While libdeflate is present in Homebrew, it doesn't appear to be in MacPorts. I'd like to have it available there as a dependency. This probably means I'll need package it, but if someone else wants to step in and do so, feel absolutely encouraged to document it on this issue.

I'll update here if I make any progress. I've packaged things for MacPorts before, but don't use it regularly, so again, happy to see someone else do it.

https://github.com/dankamongmen/notcurses/issues/2371

**Comment by dankamongmen** [comment]
https://github.com/macports/macports-ports/pull/13104 @herbygillot got on this with his usual efficiency; looks like this might happen sooner rather than later.

**Comment by mascguy** [comment]
> [macports/macports-ports#13104](https://github.com/macports/macports-ports/pull/13104) @herbygillot got on this with his usual efficiency; looks like this might happen sooner rather than later.

Just merged it!

**Comment by dankamongmen** [comment]
w00t!
