### ISSUE TITLE
deflate ram usage

### ISSUE THREAD

**Issue by smdjeff** [ebiggers/libdeflate#145]
RAM usage for deflate seems to be about 1.1MB. My packets are only around 80kB and I only have about 512KB RAM total. What settings are recommended for squeezing down the footprint for libdeflate_aligned_malloc() to around 100kB?

**Comment by ebiggers** [comment]
This is not directly supported.  If you're willing to change the source code, there are some parameters in the code which you could experiment with changing:

- `SUPPORT_NEAR_OPTIMAL_PARSING`: change to 0
- `SOFT_MAX_BLOCK_LENGTH`: decrease to maybe 75000
- `HC_MATCHFINDER_HASH3_ORDER`: decrease to maybe 11
- `HC_MATCHFINDER_HASH4_ORDER`: decrease to maybe 12

All of those combined get `sizeof(struct libdeflate_compressor)` down to 171168 bytes.  You can try other values too.

It would also be possible to reduce the sliding window size the compressor uses from the full 32768 bytes to something smaller, e.g. 16384 bytes.  But I don't remember off the top of my head if there is an easy way to do that.

In any case, please note that any of these changes will reduce the compression ratio, maybe substantially.  The code has been tuned for the current parameters, and is only tested with the current parameters.  These are just some ideas that you could try if you want to; you are on your own if you make any of these changes.

**Comment by smdjeff** [comment]
Thank you for the detailed response.

I'm at 74KB and still getting about 6x compression so I'm happy.

#define MIN_BLOCK_LENGTH	1000
#define SOFT_MAX_BLOCK_LENGTH	MIN_BLOCK_LENGTH 

And absolute smallest that will pass the STATIC_ASSERT
#define HC_MATCHFINDER_HASH3_ORDER	5
#define HC_MATCHFINDER_HASH4_ORDER	5

**Comment by ebiggers** [comment]
If it works for you, great.  Just make sure to test it well, keeping in mind that those changes will affect compression and decompression speed too.
