### ISSUE TITLE
support cross-compile

### ISSUE THREAD

**Issue by leleliu008** [ebiggers/libdeflate#147]
I wanna cross-compile this lib for Android.

I suggest define a var, say `TARGET_OS`, user can override it, default value is `uname -s`

https://github.com/ebiggers/libdeflate/blob/master/Makefile#L116

**Comment by ebiggers** [comment]
You can already build it for Android.  Just point `CC` to the appropriate compiler from the Android NDK, e.g.:

```
make CC=$HOME/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang
```

**Comment by leleliu008** [comment]
don't work on macOS. Build machine must be GNU/Linux.

**Comment by ebiggers** [comment]
It should work; what is the error message you get?  (Obviously, you'd need to replace `linux` in the NDK path.)

Note, I don't have a macOS machine to test on.

**Comment by ebiggers** [comment]
Probably the problem is the line that detects macOS builds:

```
else ifeq ($(shell uname),Darwin)
```

It should check the output of `$(CC) -dumpmachine` instead, like is done to detect Windows builds with MinGW.

A pull request would be appreciated, as I don't have a macOS machine to test on.

**Comment by leleliu008** [comment]
```patch
diff --git a/Makefile b/Makefile
index 780d99f..948ab92 100644
--- a/Makefile
+++ b/Makefile
@@ -113,7 +113,7 @@ ifneq ($(findstring -mingw,$(shell $(CC) -dumpmachine 2>/dev/null)),)
     endif

 # macOS?
-else ifeq ($(shell uname),Darwin)
+else ifeq ($(findstring -darwin,$(shell $(CC) -dumpmachine 2>/dev/null)),-darwin)
    SHARED_LIB         := libdeflate.$(SOVERSION).dylib
    SHARED_LIB_SYMLINK := libdeflate.dylib
    SHARED_LIB_CFLAGS  := -fPIC
```

this patch works for me.

do you accept github actions to test Android platform? here is a axample https://github.com/leleliu008/test/actions/runs/1644009507

I suggest using the Modern build system like CMake, meson, etc to make this project more popular.

**Comment by ebiggers** [comment]
> do you accept github actions to test Android platform? here is a axample https://github.com/leleliu008/test/actions/runs/1644009507

Any extra test coverage in GitHub Actions would be appreciated.  This would require the Android NDK; perhaps you could use the "cache" action to avoid having to download it every time?   And I assume that you have only cross-compiling in mind, and not actually running it in an Android emulator?  

> I suggest using the Modern build system like CMake, meson, etc to make this project more popular.

There has been discussion of this on https://github.com/ebiggers/libdeflate/pull/101.  CMake support might get added at some point, as people have been asking for it, but it would need to replace the current `Makefile` so that there aren't multiple build systems.

**Comment by leleliu008** [comment]
Android NDK has been installed on all GitHub Actions Virtual Environment, so we don't need to install it.

we just make sure this project can be built for Android, we don't need to verify if it can be run on real device.
