### ISSUE TITLE
build error on Solaris: conflicting types for ‘len_t’

### ISSUE THREAD

**Issue by ckerr** [ebiggers/libdeflate#159]
Solaris is not the most common OS to come across in 2022, so it's debatable how important this issue is. Still, the fix looks easy enough so I thought I'd at least report it. `len_t` is nonstandard AFAICT, but that's not stopping Solaris from declaring it in sys/types.h:

>   /export/home/user/buildAgent/work/1f3bff43dd55cfe9/_build/third-party/deflate/src/deflate/lib/deflate_decompress.c:104:12: error: conflicting types for ‘len_t’
19:13:56    typedef u8 len_t;
19:13:56               ^~~~~
19:13:56   In file included from /usr/include/string.h:15:0,
19:13:56                    from /export/home/user/buildAgent/work/1f3bff43dd55cfe9/_build/third-party/deflate/src/deflate/lib/lib_common.h:64,
19:13:56                    from /export/home/user/buildAgent/work/1f3bff43dd55cfe9/_build/third-party/deflate/src/deflate/lib/unaligned.h:8,
19:13:56                    from /export/home/user/buildAgent/work/1f3bff43dd55cfe9/_build/third-party/deflate/src/deflate/lib/deflate_decompress.c:50:
19:13:56   /usr/include/sys/types.h:240:22: note: previous declaration of ‘len_t’ was here
19:13:56    typedef u_longlong_t len_t;
19:13:56                         ^~~~~

If you're OK with the type in `lib/deflate_compress.c` being renamed to something like `dfllen_t`, I'd be happy to PR it.

**Comment by ebiggers** [comment]
Thanks for the report.  This typedef isn't important, so I'm just going to remove it.
