### ISSUE TITLE
libdeflate CPU utilization quickly flattens out with increased threads

### ISSUE THREAD

**Issue by mebbert** [ebiggers/libdeflate#170]
Hello,
I recently heard about `libdeflate` and it's performance gains over `zlib`, and was excited to try it out in a bioinformatics tool (`samtools`) that's commonly used with genomics data.

I did a comparison between `samtools + zlib`, `samtools + libdeflate`, and another tool called `sambamba` (not sure what compression library it uses). You can see my full post here: [Samtools sort: most efficient memory and thread settings for many samples on a cluster](https://bioinformatics.stackexchange.com/questions/18538/samtools-sort-most-efficient-memory-and-thread-settings-for-many-samples-on-a-c)

In short, I compare overall performance (measured by time), but I also wanted to see how well each tool could utilize the CPUs allotted to it. I was surprised to see that `samtools + libdeflate` flattens out very quickly and is unable to fully utilize allotted CPUs as well as the other two configurations (**Fig. 1**). I assume this boils down to `libdeflate`, but maybe it's more complicated than that.

In either case, I wanted to report what I found here directly so that you can either address or rebut what I posted.

And thank you for your work. We need more efficient tools like `libdeflate`!

**Figure 1: Requested CPUs vs. CPU utilization for samtools + zlib, samtools + libdeflate (Lsamtools), and sambamba**

<img width="2025" alt="CPUs vs. CPU utilization" src="https://user-images.githubusercontent.com/1953713/155849945-bc59b603-fdb7-4267-9584-36d1aa45f468.png">

**Comment by ebiggers** [comment]
libdeflate doesn't have any shared mutable data or do any locking, so there's no inherent limit to how much it can scale up --- it can handle however many concurrent compression/decompressions applications want to do.

Are you sure that the bottleneck in your application is the CPU?  Perhaps since libdeflate is faster than zlib, it it simply doesn't need the CPU for as long, causing I/O to become the bottleneck of your application...

**Comment by ebiggers** [comment]
I'm not familiar with the application, but I'd expect the difference to be something other than compression/decompression.

**Comment by ebiggers** [comment]
Okay, I assumed you were using the same compression format (DEFLATE) in all three, hence why you were comparing them.  If you can choose the compression format that opens up more options.  In general, the LZ4 compression format results in faster compression and decompression, but a worse compression ratio than DEFLATE.

Anyway, it's not clear what you're trying to accomplish with this issue.  You need to decide what your goal actually is, and optimize for that goal.  Probably maxing out your CPU is not your goal.

**Comment by mebbert** [comment]
Thanks for the info. Very helpful.

I have two simple goals:
1. Determining the fastest way to process a single samples as fast as possible (hence the time comparison)
2. Optimizing the CPU and Mem parameters to process tens of thousands of samples without wasting resources (hence the plot above). If using `samtools + libdeflate` (for whatever reason the CPUs aren't being used at full capacity) it wouldn't make any sense to request more than 3-4 CPUs per job on the cluster.

The reason I posted this issue was simply to offer feedback in case it was helpful. Clearly it was not helpful.
