### ISSUE TITLE
add possibility to build with clang on windows

### ISSUE THREAD

**Issue by AndreyMlashkin** [ebiggers/libdeflate#174]
If I build with clang on windows, makefile tries to create an *.so file

   Creating library libdeflate.so.lib and object libdeflate.so.exp
LINK : fatal error LNK1561: entry point must be defined
clang-cl: error: linker command failed with exit code 1561 (use -v to see invocation)
make: *** [Makefile:232: libdeflate.so.0] Error 25
make: *** Waiting for unfinished jobs....
  CCLD     gzip
clang-cl: warning: unknown argument ignored in clang-cl: '-fomit-frame-pointer' [-Wunknown-argument]
clang-cl: warning: unknown argument ignored in clang-cl: '-std=c99' [-Wunknown-argument]
clang-cl: warning: argument unused during compilation: '-O3' [-Wunused-command-line-argument]

**Comment by ebiggers** [comment]
Wasn't this already fixed by commit 478abccb812c0baabfc12528bf2272e3e081df96?  If not, please open a pull request to fix it.

**Comment by AndreyMlashkin** [comment]
Yes, that fixes the problem, thank you!
