### ISSUE TITLE
Haiku doesn't support hard links

### ISSUE THREAD

**Issue by Begasus** [ebiggers/libdeflate#175]
Hello, today after some talks on IRC I've started working on our port for libdeflate on Haiku, I created a patch that enables a full build/install on Haiku, would be nice if someone could review it and if need be I could create a PR here to upstream our patch.

https://github.com/haikuports/haikuports/pull/6765/files

**EDIT** patch was created on comments given on IRC, so although I created it, it's a group effort :)

**Comment by ebiggers** [comment]
Can you create a pull request here?  Thanks!

**Comment by Begasus** [comment]
Done :)
