### ISSUE TITLE
Installation on linux

### ISSUE THREAD

**Issue by andreasdc** [ebiggers/libdeflate#179]
How to install libdeflate on linux?

**Comment by ebiggers** [comment]
You already closed this issue, but just to answer this quickly: install it using your distro's package manager, or build and install from source code as described in the README.md file.

**Comment by andreasdc** [comment]
> You already closed this issue, but just to answer this quickly: install it using your distro's package manager, or build and install from source code as described in the README.md file.

I found it impossible/really hard to install, but I found the issue and it works good. :)
