### ISSUE TITLE
[Question]  How to disable avx, avx2, avx512 and so on ?

### ISSUE THREAD

**Issue by ebachard** [ebiggers/libdeflate#180]
Hello, 

I'm cross-compiling libdeflate using mingw on Linux, and I'd like to completly disable avx* asm (to avoid crash because "Illegal instruction" on machine were they are disabled), and I didn"t find a -clean- way yet.

Thanks in advance for any suggestion :-)

With best regards,
Eric Bachard

**Comment by ebiggers** [comment]
Unless you are explicitly telling the compiler to assume that these instructions are present (e.g. by adding `-march=native` to `CFLAGS`), then libdeflate only uses these instructions if the CPU supports them at runtime, as detected by the cpuid instruction.  So you should not have any problem.

**Comment by ebachard** [comment]
I have simply added  CFLAGS=${CFLAGS}:"-march=native"
````
me@ma-machine:/usr/local/cross-tools/x86_64-w64-mingw32/lib$ nm -a libdeflate.a | grep avx
0000000000000230 t adler32_avx2
0000000000000400 t adler32_avx512bw
0000000000000110 t crc32_pclmul_avx

````
... looks like it works. I'll give it a try tomorrow on a true Windows (not using this OS at home). 

Thanks a lot !

**Comment by ebiggers** [comment]
To be clear, you should **not** use `-march=native`.

**Comment by ebachard** [comment]
Ah, ok, apologies, I misunderstood what you wrote.

currently I can build using:
````
-no-avx  -mtune=generic
````

 Is it ok ?

**Comment by ebiggers** [comment]
I recommend just using the default options.  Both gcc and clang target "generic" x86_64 by default.

Are you actually experiencing a specific problem (the code crashing), or is this just theoretical?

**Comment by ebachard** [comment]
I'll try to explain : 

I've created an application using a lot of dependencies, working well on Linux. For the development, I'm using Linux (exclusively) and I do cross compilation for Windows (7+, any machine as target), using mingw.  

There is no problem on Linux, but it seems to be broken on Windows. Works fine with wine though (excepted for some specific issues like sound recording and threads).

On Windows, at launch, the only feedback I got is  "Illegal instruction".  

IMHO, the problem is,  Intel did something wrong with avx2 and avx512 instructions, no longer available on recent Windows versions, and causing this instant crash.

After some research on the web, it appears my current machine (Tiger Lake with avx2, avx512 and so on) detects everything very well and build time, and adds those instructions in the binaries. And since I discovered the problem, I'm searching for solutions... 

The first step is to rebuild everything without avx* asm instructions. I think I'm close, since I already fixed : OpenCV, SDL2, ffmpeg, and most of the dependencies). libdeflate is one of the last. Once done, I'll have to retry all tests on Windows, until I figure out completely what happens.

Apologies for my poor english, I'm not native speaker :-)

**Comment by ebiggers** [comment]
Software containing AVX* instructions is not necessarily a problem, as normally software uses these instructions conditionally based on CPU support at runtime.  As I've said, this is exactly what libdeflate does, unless you choose to add a compiler flag that tells the compiler that these instructions are always available.  If you add a such a flag, then you get what you asked for.

Are you sure that your problem is even related to AVX* instructions?

**Comment by ebachard** [comment]
I'm not 100% sure, but there are a lot of examples on the web:
See :
- https://stackoverflow.com/questions/56621809/getting-illegal-instruction-while-running-a-basic-avx512-code
- https://community.intel.com/t5/Intel-C-Compiler/Illegal-instruction-when-running-AVX-program/m-p/1022837
- https://github.com/google/jax/issues/2906
- https://github.com/tesseract-ocr/tesseract/issues/2911
