### ISSUE TITLE
Any trouble to use in webserver like nginx? 

### ISSUE THREAD

**Issue by osevan** [ebiggers/libdeflate#183]
Can i use this library in webserver? 

Thanks and

Best regards

**Comment by osevan** [comment]
I think yes,because no stream supportm

**Comment by ebiggers** [comment]
I'm not an expert in every use of DEFLATE.  It looks like HTTP compression works at the HTTP resource level, and the whole resource is compressed as a single stream.  So libdeflate should work well for serving small to moderate-sized files, but probably not for large ones where streaming support would be needed.
