### ISSUE TITLE
Whether this library can be used to compress the net load of IP packets?

### ISSUE THREAD

**Issue by myonlystarWang** [ebiggers/libdeflate#184]
Hi,
     I'm new to libdeflate project.Therefore, I want to know whether it can be used to compress IP packets(just the payload)?

**Comment by ebiggers** [comment]
There are thousands of applications where the DEFLATE compression format is used; I'm not an expert in every one.  As documented, libdeflate doesn't support streaming.  So if packets are being compressed individually then libdeflate would work, but if state needs to be kept across packets when it wouldn't work.
