### ISSUE TITLE
import library name with mingw

### ISSUE THREAD

**Issue by vtorri** [ebiggers/libdeflate#190]
the import library name suffi is often .dll.a and not .lib. Agree to use

    SHARED_LIB_LDFLAGS := -Wl,--out-implib,libdeflate.dll.a \

in Makefile ? If yes, i can do a PR

**Comment by ebiggers** [comment]
`.lib` appears to be the Windows convention, e.g. see https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#creating-an-import-library.  So I'm thinking it shouldn't be changed.

**Comment by vtorri** [comment]
and the static lib has also the .lib suffix...
that's why dll.a is better. also the name says that it is explicitely a file related to the dll.

anyway, do what you want until the link is correct when linking with ld (see https://sourceware.org/binutils/docs/ld/WIN32.html section "direct linking to a dll")

**Comment by tansy** [comment]
All libraries in all mingw distributions I have (from 3.4 to date) use "\*nix" convention (\`.a', \`.dll.a'). Even rust guys recognise that: [Windows: Static libraries should end with .a not .lib when using MinGW/GCC](https://github.com/rust-lang/rust/issues/43749).

**Comment by ebiggers** [comment]
I thought that the point of providing an import library is because Visual Studio requires it in order to link to the DLL.  (MinGW does not require it.)  So doesn't it make sense to use the Windows naming convention for it?

**Comment by vtorri** [comment]
import lib is not necessary for a DLL with VS, you can use a def file (https://docs.microsoft.com/en-us/cpp/build/reference/module-definition-dot-def-files?view=msvc-170). def files are also supported with ld.

**Comment by tansy** [comment]
> because Visual Studio requires it in order to link to the DLL
> doesn't it make sense to use the Windows naming convention for it?

Yes, if this particular naming (.lib) is required. If VS can accept mingw naming (.dll.a) then keeping it makes sense to indicate origin, mingw here. [It seems](https://web.archive.org/web/20201112024859/http://www.mingw.org/wiki/Specify_the_libraries_for_the_linker_to_use) that mingw-gcc can accept VS lib; don't know about opposite direction. [It's apparently true](https://stackoverflow.com/a/7619995/8406172) for dynamic libs only, not static.

**Comment by vtorri** [comment]
I have just tried with zlib (import lib : libz.dll.a) and the function zlibVersion(). The program compiles and links with Visual Studio, and prints the zlib version when I execute it.

**Comment by vtorri** [comment]
any news on this ?

**Comment by vtorri** [comment]
btw, msys2 patch: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libdeflate/001-libdeflate-makefile-mingw-fix.patch

**Comment by kmilos** [comment]
This (and many other handcrafted Makefile problems) should really be automatically handled by switching to either CMake (https://github.com/ebiggers/libdeflate/pull/101) or Meson (https://github.com/ebiggers/libdeflate/issues/191).

**Comment by vtorri** [comment]
my personal preference is by far meson. If there is a preference for meson from maintainers, i can try to write it (I've already written meson files  for my personal projects).

**Comment by vtorri** [comment]
note that meson automatically deals with the dll/stattic lib extensions (unix, mingw, VS) without hack. It aulso installs automatically the dll in $prefix/bin on mingw
