### ISSUE TITLE
feature request: meson build system

### ISSUE THREAD

**Issue by vtorri** [ebiggers/libdeflate#191]
Makefile is nice and fast, but meson can handle options in an easier nice syntax close to python (far far better than cmake). It is also very fast

do you agree of such build system ? I can do a PR if you want

**Comment by data-man** [comment]
> meson can handle options in an easier nice syntax close to python

And https://muon.build too.

>  It is also very fast

muon even faster. :)

**Comment by vtorri** [comment]
@data-man interesting, muon+samourai == build system in C :-)

**Comment by ebiggers** [comment]
There have been a lot more requests for CMake, including an existing partially-complete pull request (https://github.com/ebiggers/libdeflate/pull/101), so that's the one I'd probably go with if I were to change to a different build system.

**Comment by ebiggers** [comment]
Closing, as I'm going with CMake instead.
