### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#20]
I'm trying to reduce build system duplication in Squash (see https://github.com/quixdb/squash/issues/202 for the background).  Would you be interested in a CMake-based system for libdeflate?

**Comment by ebiggers** [comment]
Maybe if lots of people are interested in CMake in particular, but for now I'm not very excited about having to maintain another build system, and then possibly having more people come in and want to add their own favorite build system.  And I think the simple Makefile is nice for most people (just run 'make').

It's also still the case that libdeflate's library source files can be compiled without any special configuration, so in that sense the "build system" doesn't even do a whole lot .

**Comment by nemequ** [comment]
I can understand that.  Some people are really into the idea, some aren't.  Ping me if you change your mind.

**Comment by bsergean** [comment]
Hi there, here's my attempt at making such a cmake file -> https://github.com/ebiggers/libdeflate/pull/101

I feel like cmake is becoming a standard for building C/C++ so even if its syntax is questionable or rather not as simple as some other language build system, it's better than the status quo in my opinion.

Anyway you guys can tell me what you think.
