### ISSUE TITLE
Compile failures with clang-3.7 and icc 16

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#21]
https://travis-ci.org/quixdb/squash/builds/173186455

I checked clang-3.7 on an Ubuntu 14.04 VM and the errors happen with the Makefile included in libdeflate, too.

**Comment by nemequ** [comment]
If you want, I'd be willing to put together a Travis CI config file for libdeflate.  That would make it easier to spot these issues and test fixes…

**Comment by ebiggers** [comment]
Thanks, the problem with clang 3.7 was that clang 3.7 introduced the 'target' function attribute, but target-specific intrinsics can't be used in 'target' attribute functions until clang 3.8.  I worked around this by checking the clang version number (unfortunately I could not think of a better way).

icc may have a similar problem but I don't have it available to test right now.

I'm definitely interested in improving how libdeflate is tested, so feel free to submit a proposal.  Do note that I don't want to tie the project too closely with 3rd party services like Github and Travis CI, but in general I am all for better testing.  Note that I recently added my own test script (see `tools/run_tests.sh`).

**Comment by nemequ** [comment]
For the undefined identifiers, including `immintrin.h` did the trick.  I just added `-include immintrin.h` to my cflags, but I assume there is a reasonable place in the code to do it.

Once that was fixed I started seeing

```
lib/decompress_impl.h(36): warning #3550: target attribute not recognized
  static enum libdeflate_result ATTRIBUTES
                                ^
```

ICC just doesn't support the bmi2 attribute.  It also doesn't have `__builtin_ia32_pdep_di`.  I fixed it with

```diff
diff --git a/common/compiler_gcc.h b/common/compiler_gcc.h
index 6b17dda..f1fec3e 100644
--- a/common/compiler_gcc.h
+++ b/common/compiler_gcc.h
@@ -63,7 +63,7 @@
 
 #define COMPILER_SUPPORTS_BMI2_TARGET                          \
        (COMPILER_SUPPORTS_TARGET_FUNCTION_ATTRIBUTE &&         \
-        (GCC_PREREQ(4, 7) || __has_builtin(__builtin_ia32_pdep_di)))
+        ((!defined(__INTEL_COMPILER) && GCC_PREREQ(4, 7)) || __has_builtin(__builtin_ia32_pdep_di)))
 
 #define COMPILER_SUPPORTS_AVX2_TARGET                          \
        (COMPILER_SUPPORTS_TARGET_FUNCTION_ATTRIBUTE &&         \
```

FWIW icc 17 (latest) behaves the same.

**Comment by ebiggers** [comment]
Thanks for the suggestion.  For now I can't test icc and I don't know which icc version was actually the first to support each of the features I am testing gcc versions for.  So until I or someone else is able to determine proper feature checks for icc, I am going to be conservative and make the gcc version checks always evaluate to false for icc.

If you test the latest commit (e79444be27a5) all the compilers you're testing should work.

**Comment by nemequ** [comment]
If you're interested in supporting ICC, Intel does offer [free licenses for open source development](https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor).

In theory checking `__GNUC__` and friends should work (though ICC also supports MSVC features, so checking `_MSC_VER` can be helpful, too).  Unfortunately ICC's support for GCC and MSVC features isn't perfect, so every once in a while one must make special allowances for bugs in ICC.  IMHO having GCC feature checks return false is a bit heavy-handed… AFAICT this is the only place where ICC masquerading as GCC doesn't work, so I think it would make sense to just add this one exception and deal with any more issues as they appear.

**Comment by nemequ** [comment]
FWIW, if you don't want to apply for a license I'm willing to help out with this.  I don't want to try to figure out when exactly stuff was added (Intel's documentation doesn't say because they expect you to use GCC's, so the only way is trying various older versions), but I can at least test ICC 16 / 17 for you.

**Comment by ebiggers** [comment]
You can help if you're interested!  I mainly just don't want to enable things until someone has tested them.  I'd suggest adding an `ICC_PREREQ()` macro to go along with `GCC_PREREQ()` and `CLANG_PREREQ()`, then going through each of the `GCC_PREREQ()` checks and testing if the feature works with icc 16, and if so also enabling it if `ICC_PREREQ(16)` is true.  (Or if you happen to know that a feature definitely works in an older version than 16 then you can use that version.)

**Comment by ebiggers** [comment]
Closing, since the original compile failures were resolved, as far I know.  If anyone wants additional optimizations for icc, please create a new issue or pull request(s).
