### ISSUE TITLE
Performance down between gcc-7 and gcc-10 on our build chain

### ISSUE THREAD

**Issue by synopse** [ebiggers/libdeflate#216]
In our Open Source framework, we tried to compile the latest 1.13 revision, but got lower performance than with 1.7.
 https://github.com/synopse/mORMot2/commit/a2ae3aa3abcf3bdd45e7d2dc9262bb3635596ed0#r81675960

Revision 1.7 was compiled with gcc-7 some time ago, which is not available any more on my PC.
With revision 1.13, and the same compilation script, and with gcc-10 or gcc-9 on my newer Debian, our benchmarks show lower performance on x86_64.
I don't claim it is libdeflate fault - it may be due to the gcc compiler we use or unefficient compilation flags.
But I filled an issue here since you asked https://github.com/synopse/mORMot2/commit/a2ae3aa3abcf3bdd45e7d2dc9262bb3635596ed0#r81675960 ;)

We compile from this material:
https://github.com/synopse/mORMot2/tree/master/res/static/libdeflate
The only change to the source is that libdeflate_malloc/free are defined as exported symbols to redirect to the pascal/FPC MM.
The manual script (no make file) is available at https://github.com/synopse/mORMot2/blob/master/res/static/libdeflate/compile-fpc-x86_64-linux.sh - it was tuned to fit the FPC expectations.

If anyone has any hint, they are welcome, since I am no C expert, and I was not able to find out the reason of the performance drop.

**Comment by ebiggers** [comment]
A couple questions:

* How much did the performance decrease by?
* Which specific functionality of libdeflate are you seeing this problem with (compression, decompression, hashing)?  If compression, what compression levels?

**Comment by synopse** [comment]
We just use regular compression then decompression of a 3.8MB of compressible input, with default level 6.

With lib 1.7:
```
  - TAlgoCompress: 1,218 assertions passed  873.27ms
     TAlgoSynLZ 3.8 MB->2.2 MB: comp 245.4MB/s decomp 365.4MB/s
     TAlgoRleLZ 3.8 MB->2.1 MB: comp 160.5MB/s decomp 340.7MB/s
     TAlgoRle 3.8 MB->3.3 MB: comp 417.5MB/s decomp 3.7GB/s
     TAlgoLizard 3.8 MB->2.1 MB: comp 27MB/s decomp 319.1MB/s
     TAlgoLizardFast 3.8 MB->2.4 MB: comp 133.2MB/s decomp 342.5MB/s
     TAlgoLizardHuffman 3.8 MB->2 MB: comp 13.5MB/s decomp 224.9MB/s
     TAlgoDeflate 3.8 MB->1.7 MB: comp 47.8MB/s decomp 400MB/s
     TAlgoDeflateFast 3.8 MB->1.7 MB: comp 64.8MB/s decomp 370.3MB/s
 ```
With our own-compiled 1.13, the performance is about 200MB/s IIRC.
I can recompile and run again the tests later.

**Comment by synopse** [comment]
I recompiled libdeflate 1.13 with gcc-10.

The hashing performance is the same, or slightly better:
```
     2500 crc32c in 229us i.e. 10.4M/s or 22.6 GB/s
     2500 xxhash32 in 816us i.e. 2.9M/s or 6.3 GB/s
     2500 crc32 in 236us i.e. 10.1M/s or 22 GB/s
     2500 adler32 in 255us i.e. 9.3M/s or 20.3 GB/s
     2500 hash32 in 451us i.e. 5.2M/s or 11.5 GB/s
     2500 aesnihash in 222us i.e. 10.7M/s or 23.4 GB/s
```
(crc32 + adler32 are from libdeflate)

But the compression performance is lower, with lib 1.13:
```
    TAlgoSynLZ 3.8 MB->2.2 MB: comp 257.5MB/s decomp 363.2MB/s
     TAlgoRleLZ 3.8 MB->2.1 MB: comp 174.9MB/s decomp 340.7MB/s
     TAlgoRle 3.8 MB->3.3 MB: comp 506.2MB/s decomp 4GB/s
     TAlgoLizard 3.8 MB->2.1 MB: comp 26.9MB/s decomp 317.8MB/s
     TAlgoLizardFast 3.8 MB->2.4 MB: comp 131.1MB/s decomp 332MB/s
     TAlgoLizardHuffman 3.8 MB->2 MB: comp 13.8MB/s decomp 232MB/s
     TAlgoDeflate 3.8 MB->1.6 MB: comp 30.9MB/s decomp 238MB/s
     TAlgoDeflateFast 3.8 MB->1.8 MB: comp 68.2MB/s decomp 257.1MB/s
  ```
  (the libdeflate numbers are TAlgoDeflate/TAlgoDeflateFast, which match level 6 and 1)

**Comment by synopse** [comment]
I recompiled the 1.7 source code with gcc-10.
And the numbers are also down:
```
     TAlgoDeflate 3.8 MB->1.7 MB: comp 30.4MB/s decomp 227.6MB/s
     TAlgoDeflateFast 3.8 MB->1.7 MB: comp 46.8MB/s decomp 203.7MB/s
```

The gcc-10 revision version is "GCC Debian 10.2.1-6".
The gcc-7 revision version is "GCC Ubuntu 7.5.0-6ubuntu2".

So this is clearly a compiler issue.

**Comment by synopse** [comment]
I attach the .a of the two compilations of 1.7 source code.
[libdeflate1.7-gcc10.zip](https://github.com/ebiggers/libdeflate/files/9386687/libdeflate1.7-gcc10.zip)
[libdeflate1.7-gcc7.zip](https://github.com/ebiggers/libdeflate/files/9386688/libdeflate1.7-gcc7.zip)

**Comment by synopse** [comment]
I renamed the title to be more explicit: it is not a libdeflate regression, but a compiler problem.

**Comment by synopse** [comment]
I guess I found it.

I removed the  `-ffreestanding` parameter, and the number are back high:
```
     TAlgoDeflate 3.8 MB->1.6 MB: comp 51.9MB/s decomp 379MB/s
     TAlgoDeflateFast 3.8 MB->1.8 MB: comp 124.9MB/s decomp 395MB/s
```
Now we observe what is expected with libdeflate 1.13: much faster compression at level 1, better compression ratio at level 6, and slightly slower decompression.

I guess we could close the issue.

**Comment by ebiggers** [comment]
Yes, you should *not* use `-ffreestanding` on its own, as it prevents the compiler from inlining `memcpy()`, which greatly reduces performance.  It sounds like you don't want a freestanding build, so your fix is correct.  But for future reference, the supported way to do a freestanding build of libdeflate is to do what `make FREESTANDING=1` does, which is to use `-ffreestanding -nostdlib -DFREESTANDING`.

**Comment by ebiggers** [comment]
https://github.com/ebiggers/libdeflate/pull/217 will make the documentation explicitly mention using a custom build system, and the `-ffreestanding` gotcha.

**Comment by synopse** [comment]
Thanks: it could help C noobs like me. ;)
