### ISSUE TITLE
Coverity Scan

### ISSUE THREAD

**Issue by JoeArizona** [ebiggers/libdeflate#22]
Hi Eric – How about putting libdeflate on Coverity Scan? It's free: https://scan.coverity.com/

Is there any downside? Maybe false positives? My impression is that Coverity is pretty good at controlling false positives, but I'm no expert.

**Comment by ebiggers** [comment]
I've used it with a larger project and it gave almost all false positives.  I am going to try it with libdeflate anyway, though --- finding even just one bug would make it worthwhile.

**Comment by ebiggers** [comment]
I set up the project (https://scan.coverity.com/projects/ebiggers-libdeflate) and ran a scan.  It found two "defects", but both are intentional and I'm not going to change anything now.  Thanks for the suggestion though!

**Comment by JoeArizona** [comment]
That's good to hear. Maybe it will be more useful at some point down the line.
