### ISSUE TITLE
CMake: Error generating build files with VS2022

### ISSUE THREAD

**Issue by rleigh-codelibre** [ebiggers/libdeflate#236]
I'm getting this error:

```
C:\Users\rleigh\AppData\Local\JetBrains\Toolbox\apps\CLion\ch-1\222.4167.35\bin\cmake\win\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:/Users/rleigh/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-1/222.4167.35/bin/ninja/win/ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\rleigh\code\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_INSTALL_PREFIX:PATH=install -G Ninja -S C:\Users\rleigh\code\libdeflate -B C:\Users\rleigh\code\libdeflate\cmake-build-debug
-- The C compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for clock_gettime
-- Looking for clock_gettime - not found
-- Looking for futimens
-- Looking for futimens - not found
-- Looking for futimes
-- Looking for futimes - not found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - not found
-- Looking for posix_madvise
-- Looking for posix_madvise - not found
-- Performing Test HAVE_STAT_NANOSECOND_PRECISION
-- Performing Test HAVE_STAT_NANOSECOND_PRECISION - Failed
-- Configuring done
-- Generating done
CMake Error:
  Running

   'C:/Users/rleigh/AppData/Local/JetBrains/Toolbox/apps/CLion/ch-1/222.4167.35/bin/ninja/win/ninja.exe' '-C' 'C:/Users/rleigh/code/libdeflate/cmake-build-debug' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:297: multiple rules generate deflate.lib [-w dupbuild=err]

  



CMake Generate step failed.  Build files cannot be regenerated correctly.
```

I'll take a closer look and open a PR once I've found what's going wrong here. /cc @bsergean

**Comment by rleigh-codelibre** [comment]
OK, this is due to

```
OUTPUT_NAME deflate
```

being used for both the shared and the static library build.  On Windows, they both create a *deflate.lib*, the DLL import library and the static library, respectively.

I would question here why we are building both the shared and static libraries with the same name, and/or building them at the same time.  Unfortunately, this is not portable.  If you just create a single library and use the standard CMake variable `BUILD_SHARED_LIBS` you can build either a shared or static library automatically (but not both at the same time).  If you use a suffix for one of them, then you can build both at once, but with different names for linking.  See https://github.com/madler/zlib/blob/master/CMakeLists.txt L186 for an example of the latter.  For the former, just delete one of the libraries and remove the SHARED/STATIC, and it will be automatically selected.

Kind regards,
Roger

**Comment by ebiggers** [comment]
Can you consider https://github.com/ebiggers/libdeflate/pull/237?

As for why I made the CMakeLists.txt define both a static library and a shared library, rather than using `BUILD_SHARED_LIBS`, it is because many users will want to build both libraries at once, e.g. anyone building a Linux package.
