### ISSUE TITLE
If -V option is included in gzip command line, program does not compress the file(s)

### ISSUE THREAD

**Issue by JoeArizona** [ebiggers/libdeflate#24]
Hi Eric:

I'm using your posted Windows 64-bit binaries of libdeflate 0.7. When using the gzip program, if I include the `-V` flag to get version and legal info, either by itself or in combination with other flags (e.g. `-kV`), the file is not compressed, no .gz file is produced, etc.

All that happens is that the version and legal info is displayed, as though -V was the sole content of the command. See the example below:

```PowerShell
PS C:\Tools\libdeflate-0.7> .\gzip -12 -k -V jQuery-3.2.1-min-CDNJS.js
gzip compression program v0.7
Copyright 2016 Eric Biggers

This program is free software which may be modified and/or redistributed
under the terms of the MIT license.  There is NO WARRANTY, to the extent
permitted by law.  See the COPYING file for details.
PS C:\Tools\libdeflate-0.7>
```

This is in Powershell on Windows 10, 64-bit. As I mentioned, I'm using your posted Windows binaries as opposed to my own builds.

If I simply remove the -V flag, the gzip program works as expected, I get a compressed file, etc.

Ideas?

**Comment by jibsen** [comment]
I believe it is common practice to print the version info and exit returning success if the command-line argument for version info is present. See for instance [here](https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html). I tried gzip, and it appears to do the same.

**Comment by ebiggers** [comment]
Yes, as @jibsen stated, this is the standard behavior.  Printing the version is normally its own operation, not something you can do in combination with other operations.

**Comment by JoeArizona** [comment]
Roger that.
