### ISSUE TITLE
Beaten by Huffman-only in some PNGs

### ISSUE THREAD

**Issue by andrews05** [ebiggers/libdeflate#241]
Testing against this image using oxipng: https://stsci-opo.org/STScI-01G8GYD8B1H306SSPR4MY6NGN0.png
Libdeflate at level 12 compresses the IDAT to 48,294,850. (No lower level is better)
Zlib at level 1 with a Huffman-only strategy compresses to 45,407,609.
I also tested this separately from oxipng by extracting the decompressed idat and tested libdeflate's gzip vs pigz (which has a --huffman option). I can upload the idat if it would be helpful.

I realise libdeflate isn't going to win against zlib every single time, but I thought this was an interesting one because it's a sizeable difference and the Huffman strategy is of course much faster.

**Comment by ebiggers** [comment]
Thanks, it's an interesting file.  I extracted the IDAT and ran some tests.  Changing libdeflate to use a minimum match length of 11 or higher results in a compressed IDAT of length 45,282,522 bytes at compression level 2.  It might be best to implement this as an improvement of the existing heuristic (added in libdeflate v1.9) that automatically selects a minimum match length.  Levels 1 and 10-12 don't use that heuristic, though, so something else would be needed there.

**Comment by andrews05** [comment]
Since the better compression is a very fast method, could levels 10-12 simply try performing that same method in addition to their normal method?

**Comment by tansy** [comment]
Specific cases, exceptions are exceptional by definition.
Analogical effect can be observed with artificial data, like [spewG](https://gitlab.com/bzip2/bzip2/-/blob/master/spewG.c) form bzip2.
```
104857600 spewG.out
 25197864 spewG.out.pigz-H
   254506 spewG.out.gzip-ld-9
   217062 spewG.out.gzip-ld-12
   211162 spewG.out.hwzip
   203509 spewG.out.pigz-9
   187502 spewG.out.gzip-9
```
It's not in the same category, where Huffman-only strategy wins but, here, gzip wins by a large margin.
I wouldn't attribute more value than there is.

**Comment by ebiggers** [comment]
The IDAT of `STScI-01G8GYD8B1H306SSPR4MY6NGN0.png` (from above) now compresses to 45,281,576 bytes at level 12.

**Comment by txtsd** [comment]
Nice! Can't wait till this lands in a release.

**Comment by andrews05** [comment]
Brilliant, thank you again!
