### ISSUE TITLE
cmake not supporting custom CMAKE_INSTALL_PREFIX everywhere

### ISSUE THREAD

**Issue by gcflymoto** [ebiggers/libdeflate#243]
Hi, thank you for an excellent library. In our build systems we had to 

1. modify the generated makefile to replace a hard-coded /usr/local/bin to install use $CMAKE_INSTALL_PREFIX as is referenced in the rest of the file
2.  Replace /usr/local in the generated pkgconfig and cmake file to the final installation path of the library
```
export CMAKE_INSTALL_PREFIX=${target_directory}
export DESTDIR=
cmake -B build \
    && sed -i 's,/usr/local/bin,${CMAKE_INSTALL_PREFIX}/bin,' build/programs/cmake_install.cmake \
    && cmake --build build --target all --config Release --verbose \
    && cmake --install build --config Release --prefix ${target_directory}
cd ${target_directory}
sed -i 's,/usr/local/,<final_install_path_prefx>/libdeflate/1.14/,' lib64/pkgconfig/libdeflate.pc lib64/cmake/libdeflate/libdeflate-targets.cmake
```
otherwise cmak is trying to install into /usr/local which is not where we want it installed.

**Comment by ebiggers** [comment]
CMake variables such as `CMAKE_INSTALL_PREFIX` need to be set with `-D`, for example  `cmake -B build -DCMAKE_INSTALL_PREFIX=${target_directory}`.  CMake only recognizes specific [environmental variables](https://cmake.org/cmake/help/latest/manual/cmake-env-variables.7.html) from the environment.  This is the same for all CMake based projects.
