### ISSUE TITLE
Compressing a little more

### ISSUE THREAD

**Issue by andrews05** [ebiggers/libdeflate#244]
I was fiddling with the max_search_depth and num_optim_passes settings to see how much more compression could be gained by maxing things out.
Increasing max_search_depth from 150 to 300 was generally favourable, with some files being 1% smaller - small, but not insignificant, and it wasn't tangibly slower either. (600 didn't show any improvement)
Increasing num_optim_passes from 4 to 5 or 6 showed further notable improvement in some files, though strangely regressed others.
So just wondering what your thoughts are on possibly allowing stronger compression. Is there room for a level 13? Could level 12 be strengthened? Could the configuration options be exposed in the API? None of the above?

**Comment by andrews05** [comment]
As an example, here's a png whose idat compresses worse at level 12 (59696 bytes) than it does at level 11 (58995 bytes). Increasing max_search_depth from 150 to 300 makes level 12 compress better (58553 bytes).
Would there be any downsides to making this change?

![snowballs](https://user-images.githubusercontent.com/4584038/203931545-6d31c9c2-af46-46ed-9130-27e2b5018fb8.png)

**Comment by ebiggers** [comment]
Yes, it might make sense to further increase the `max_search_depth` at level 12, and maybe also 10-11.  (I already increased in it v1.9.)  But I'll need to do some experiments.  There are always possible downsides.

I'd prefer not to expose implementation details like `max_search_depth` in the API.

**Comment by andrews05** [comment]
Sounds good. Is it expected that going over 300 doesn't change anything, or am I just not testing on enough files?

**Comment by ebiggers** [comment]
I've made a number of changes to levels 10-12, especially 11-12, to improve compression ratio slightly.

On the PNG file given above, the compressed size of the IDAT is now 60117, 59473, and 57887 bytes at level 10, 11, and 12.  Previously it was 60516, 58989, and 59690 bytes.

**Comment by andrews05** [comment]
Thank you so much for your work here, this is really impressive :)
