### ISSUE TITLE
Users of libdeflate shouldn't require to define LIBDEFLATE_STATIC  or somehting like that.

### ISSUE THREAD

**Issue by pps83** [ebiggers/libdeflate#259]
> On Windows, you must define LIBDEFLATE_STATIC if you are linking to the static library version of libdeflate instead of the DLL.

Pretty unusual requirement. Should be removed imo, libdeflate didn't have that in older versions afaik. Even if you link to dll version, and if you you define LIBDEFLATE_STATIC it will still link and work ok.
I'm not 100%, but afaik, there is minor advantage when you declare dllimport - functions from dlls avoid indirection or something like that. In case of libdeflate it's hardly relevant. I'd suggest to completely remove it:
```
#ifndef LIBDEFLATEEXPORT
#define LIBDEFLATEEXPORT
#endif
```
when building, inside lib src code you'd define it to:
```
if msvc && dll:
  define LIBDEFLATEEXPORT dllexport
else if gcc:
  define LIBDEFLATEEXPORT visibility default
```

https://github.com/ebiggers/libdeflate/blob/cff853640e4a1d7aef8051cb8e7a6fabe454b8f4/libdeflate.h#L20

**Comment by ebiggers** [comment]
Well, it used to be `LIBDEFLATE_DLL` to use the DLL, but that didn't work well with pkg-config (https://github.com/ebiggers/libdeflate/issues/229) so I changed it to `LIBDEFLATE_STATIC` to use the static library.  Lots of libraries use one method or the other, so it's not unusual.

That being said, if `dllimport` is really not necessary we could drop it.  I was not aware that was possible.  Is there any document that describes the best practices here?

**Comment by pps83** [comment]
> Well, it used to be `LIBDEFLATE_DLL` to use the DLL, but that didn't work well with pkg-config (#229) so I changed it to `LIBDEFLATE_STATIC` to use the static library. Lots of libraries use one method or the other, so it's not unusual.
> 
> That being said, if `dllimport` is really not necessary we could drop it. I was not aware that was possible. Is there any document that describes the best practices here?

https://gcc.gnu.org/wiki/Visibility last section there tells how to properly do it. 

about dllimpotr: https://stackoverflow.com/questions/8863193/what-does-declspecdllimport-really-mean in short, " This is a code size and speed optimisation". It's irrelevant for libdeflate

**Comment by ebiggers** [comment]
> https://gcc.gnu.org/wiki/Visibility last section there tells how to properly do it.

Well, that actually says to use `dllimport`.

Anyway, https://github.com/ebiggers/libdeflate/pull/263 brings back LIBDEFLATE_DLL but makes it clear that it is optional.

**Comment by pps83** [comment]
I'd suggest to also do something similar to what I've done in my local copy:

https://github.com/ebiggers/libdeflate/commit/9a97f4166d36ba2069c2f522c86869d1df0153eb
