### ISSUE TITLE
LIBDEFLATEEXPORT+LIBDEFLATEAPI are redundunt and shouldn't be part of public libdeflate.h header

### ISSUE THREAD

**Issue by pps83** [ebiggers/libdeflate#267]
Here's how it should be imo
https://github.com/ebiggers/libdeflate/commit/3b2388006239efddeb3ee8626438766f7b0bd3b1

https://github.com/ebiggers/libdeflate/blob/6519a164e9cafe17493a4226f38e0563750530b2/libdeflate.h#L25

Also, unrelated, but you cannot include headers inside extern c block. This will lead to errors in msvc if these headers weren't included before including libdeflate.h in some c++ code.

**Comment by ebiggers** [comment]
> Here's how it should be imo

https://github.com/ebiggers/libdeflate/pull/269 will do this.  I made some changes from your version:

- Retain support for LIBDEFLATE_DLL in libdeflate.h
- Keep using `force_align_arg_pointer` in all the cases where it was used before
- Add a better explanation to the commit message
- Split the `#include` changes into a different commit and pull request

> you cannot include headers inside extern c block.

Done by https://github.com/ebiggers/libdeflate/pull/268
