### ISSUE TITLE
How about implementing PKZIP or zlib compatible?

### ISSUE THREAD

**Issue by kanryu** [ebiggers/libdeflate#27]
Hi,

I've been looking for an alternative to zlib and have found libdeflate, but since the purpose is the deployment of the zip archive, I can not use your library as it is.

If you'd like to do that, if libdeflate supports compression and expansion of pkzip itself, or with an optional wrapper, it gets a far greater need than deflate-only support You can do it.

There is an implementation called minizip in zlib/contrib, which will be helpful compared with making it from scratch. Or just prepare an interface compatible with zlib. I will make programs using real with minizip so you do not need to prepare everything.

Thank you.

**Comment by JosePineiro** [comment]
I write one in c# using libdeflate

Please, see it at https://github.com/JosePineiro/LittleZip

**Comment by ebiggers** [comment]
Closing since the Zip file format and zlib API compatability is out of scope for libdeflate.
