### ISSUE TITLE
CMake vs old Makefile - MinGW: breaking change of libs extension & static lib name

### ISSUE THREAD

**Issue by SpaceIm** [ebiggers/libdeflate#274]
Before 1.15, static lib name for MinGW was `libdeflatestatic.lib` and import lib of dll `libdeflate.lib`:
https://github.com/ebiggers/libdeflate/blob/v1.14/Makefile#L96-L98
https://github.com/ebiggers/libdeflate/blob/v1.14/Makefile#L191

In CMakeLists of 1.15, static lib name for MinGW is `libdeflate.a` and import lib of dll `libdeflate.dll.a`: https://github.com/ebiggers/libdeflate/blob/v1.15/CMakeLists.txt#L183-L190

Is it intended?

**Comment by ebiggers** [comment]
Yes, see NEWS.md:

```
                                                                                 
* When libdeflate is built with MinGW, the static library and import library are 
  now named using the MinGW convention (`*.a` and `*.dll.a`) instead of the      
  Visual Studio convention.  This affects the official Windows binaries.
```

Note that this change was made for https://github.com/ebiggers/libdeflate/issues/190, and it is unrelated to the migration to CMake.
