### ISSUE TITLE
Build fails on armv7l

### ISSUE THREAD

**Issue by mobinmob** [ebiggers/libdeflate#276]
I am trying to build libdeflate v1.15  on voidlinux ([PR](https://github.com/void-linux/void-packages/pull/41014)) as a dependency for notcurses. Cross-compilation fails for an armv7l target with: 

```
tmp/ccyCwo01.s:1367: Error: selected processor does not support `crc32w r9,r9,r1' in ARM mode
```
Full build log is available on github actions ci:
https://github.com/void-linux/void-packages/actions/runs/3668294626/jobs/6201323209

**Comment by ebiggers** [comment]
Which gcc version are you using?  There was a gcc bug that caused this (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104439), but libdeflate already avoids building the ARM crc32 code on the affected gcc versions.

**Comment by ebiggers** [comment]
To answer my own question, the log says the gcc version was 10.2.1.

https://github.com/ebiggers/libdeflate/pull/278 should fix this.

**Comment by mobinmob** [comment]
> To answer my own question, the log says the gcc version was 10.2.1.
> 
> #278 should fix this.

Thank you for taking the time to look into it and provide a fix!
