### ISSUE TITLE
Greater max_codeword_len?

### ISSUE THREAD

**Issue by JosePineiro** [ebiggers/libdeflate#28]
Your library a very fast, even at level 12
Please implement lever upper to 12.
If I am no wrong, max_codeword_len=32 are safe for zip format and not increment the compress time too much.

**Comment by ebiggers** [comment]
Actually the only artificial limit that libdeflate's compressors place on the length of Huffman codewords is that they cap the length of litlen codewords to 14 bits, while the DEFLATE format allows 15 bits.  Allowing the extra bit would improve the compression ratio only a very tiny amount in some cases.  Much more useful would be implementing a more sophisticated (but much more computationally intensive) block splitting algorithm.  I don't have time to research this anytime soon though, and if you truly want as close to the optimum DEFLATE compression ratio as possible, regardless of performance, you're currently best off using Zopfli or ECT.

**Comment by ebiggers** [comment]
Closing this since the original suggestion to increase max_codeword_len isn't very useful.
