### ISSUE TITLE
Failure to build with MSVC

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#3]
MSVC errors when it sees a `#warning`.  See https://ci.appveyor.com/project/quixdb/squash/build/308/job/6kb86lqdyspp5bkg#L2306 for an example.

The MSVC equivalent is `#pragma message("warning text goes here")`, which GCC has supported since 4.4.

**Comment by ebiggers** [comment]
There will be more than just that to get it to work properly with MSVC.  I may play around with it when I have time.

**Comment by ebiggers** [comment]
MSVC is now supported.  However, MinGW remains the recommended compiler when targeting Windows.

Closing this issue.
