### ISSUE TITLE
Speed Benchmark: libdeflate vs BWTSATAN, BSC, 7zip, ZSTD, LZ4, LZSSE, BriefLZ, Satanichi

### ISSUE THREAD

**Issue by Sanmayce** [ebiggers/libdeflate#300]
Having seen your new release (with decompression boost) immediately wanted to compare it to the usual suspects.

Included compressors:

- BWTSATAN by Powturbo, worldwide;
- BSC v.3.2.3 by Ilya Grebnov aka Gribok, Russia;
- GZ, 7zip's GZ v.22.01 by Igor Pavlov, Russia;
- BZ2, 7zip's BZ2 v.22.01 by Igor Pavlov, Russia;
- ZSTD v.1.5.2 by Yann Collet aka Cyan, France;
- LZ4 v.1.9.3 by Yann Collet aka Cyan, France;
- LZSSE by Conor Stokes, Australia;
- BriefLZ v.1.3.0 by Joergen Ibsen, Denmark;
- Satanichi, Sanmayce's texttoy, Bulgaria;
- libdeflate v.1.14 by Eric Biggers aka ebiggers, Earth.

The corresponding lines for compression:
```
timer64 bwtsatan.exe -17 "%1" "%1"
timer64 bsc-3.2.3-x64.exe e "%1" "%1.bsc" -p -b2047 -m0 -e2
timer64 7za_2201-x64.exe a -tgzip -mx=9 -mmt=8 "%1.gz" "%1"
timer64 7za_2201-x64.exe a -tbzip2 -mx=9 "%1.bz2" "%1"

timer64 zstd-v1.5.2-win64.exe --ultra -22 --long=31 --zstd=wlog=31,clog=30,hlog=30,slog=26 "%1" -o "%1.zst"
timer64 lz4_win64_v1_9_3.exe -9 "%1"

timer64 lzsse.exe -2 -l17 "%1" "%1.lzsse2"
timer64 BriefLZ_130_Intel_v19_64bit.exe --optimal -b3g "%1" "%1.blz"
timer64 Satanichi_Nakamichi_Vanilla_LITE_DD-128AES_GCC_64bit.exe "%1" "%1.Nakamichi" 20 384000 i
timer64 "gzip_libdeflate-1.14-windows-x86_64-bin.exe" -12 -f -k -S .LIBDEFLATE12 "%1"
```

Testdatafile #1, sorted by decompression time (4th column):
Size: 549,415,424 bytes
Name: SUPRAPIG_NSF_Research_Award_Abstracts_1990-2003_(134159_TXTs).tar
sha1: a793d8166508a6ad9ade22f441be74c74e2ab31b
Testmachine: laptop 'Brutalitto' AMD 4800H max turbo 4.3GHz, 8/16 cores/threads, 64GB DDR4 3200MHz, Windows 10.
```
+---------------------+---------------+-----------------+-----------------+
| [De]compressor,     | Compression,  | Compression,    | Decompression,  |
| MAX settings        | size in bytes | time in seconds,| time in seconds,|
|                     |               | Global Time     | Global Time     |
+---------------------+---------------+-----------------+-----------------+
| LZSSE               |   111,628,348 |        777.99 s |          0.50 s |
| LZ4 v.1.9.3         |   117,594,113 |         14.75 s |          0.57 s |
| Satanichi_ICL       |    75,943,684 |            N.A. |          0.90 s |
| Satanichi_CLANG     |    75,943,684 |            N.A. |          0.90 s |
| Satanichi_GCC       |    75,943,684 |            N.A. |          0.90 s |
| libdeflate v.1.14   |   102,491,715 |        163.03 s |          1.02 s |
| ZSTD v.1.5.2        |    53,719,912 |       4353.84 s |          1.07 s |
| BriefLZ v.1.3.0     |    67,012,629 |      14513.31 s |          1.78 s |
| 7zip's GZ v.22.01   |   103,296,785 |        465.44 s |          2.64 s |
| 7zip's BZ2 v.22.01  |    67,281,322 |        215.92 s |         11.09 s |
| BWTSATAN            |    39,936,842 |         31.77 s |         11.30 s |
| BSC v.3.2.3         |    40,083,210 |         37.00 s |         11.54 s |
+---------------------+---------------+-----------------+-----------------+
Note1: The decompression is done on RamDisk of size 16GB, both the compressed and the decompressed files are on it.
Note2: Decompression time is the minimum value of 3 runs.
Note3: Decompression time is the sum of LOAD+DECOMPRESS+STORE i.e. real-world decompression.
```
Obviously, your superb ZIP implementation stands for the ZIPPING sound of a bullet not a zipper, it screams that is.

**Comment by funny-falcon** [comment]
I don't get, why zstd compressed in "ultra" level instead of level comparable on compression size.

**Comment by Sanmayce** [comment]
> I don't get, why zstd compressed in "ultra" level instead of level comparable on compression size.

The short answer, decompression speed was the focus.

The goal always was to show the decompression power of all compressors, and since LZ family gets faster with higher ratio the max compression was chosen.
Ideally, all levels should be benchmarked, but then someone will not get why the rest performers are not benchmarked fully as well, then the benchmarking will turn into once again not WELL DONE since complaining about "why only AMD and not Intel, why this architecture and not that as well". 

Do you think if you match the size, the result will differ?
