### ISSUE TITLE
Version `1.8` is able to decompress data that version `1.17` cannot, but only on Windows

### ISSUE THREAD

**Issue by sumit0190** [ebiggers/libdeflate#308]
I stumbled onto this from its usage in the Python `tifffile` library. Long story short: one version of `libdeflate` - 1.8 - seems to be able to decompress a chunk of data correctly (data attached here), but other versions (I've only tried 1.17 so far) seems to fail. The weird thing is that it only happens on Windows. Here's my sample program (apologies for the hardcoded sizes, but I quickly wrote this to test my hypothesis):
[badfiledata.txt](https://github.com/ebiggers/libdeflate/files/11226283/badfiledata.txt)
```
#include "libdeflate.h"
#include <stdio.h>

int main(int argc, char **argv) {
  // Read the data and allocate output buffer
  FILE *source = fopen(argv[1], "rb");
  char in[50463];
  fread(in, 50463, 1, source);
  char out[50463 * 3];

  // Allocate decompressor and decompress
  struct libdeflate_decompressor *d = libdeflate_alloc_decompressor();
  size_t out_size = 0;
  enum libdeflate_result res =
      libdeflate_zlib_decompress(d, (void*)in, sizeof in, (void*)out, sizeof out, &out_size);

  // 0 indicates success, anything else is failure.
  printf("Decode result: %d\n", res);

  // Free up the decompressor
  libdeflate_free_decompressor(d);
  return 0;
}
```
When compiled with `VS 19.29.30037 x64`, this program returns `1` with library version 1.17, but `0` with library 1.8. Again, on Linux and macOS both versions of the library return `0`.

I simply want to understand if this is expected, I do not know enough about decompression and decoding to claim anything else. Thanks in advance. :)

**Comment by ebiggers** [comment]
Are you compiling libdeflate with MSVC, or just the program that links to it?

**Comment by sumit0190** [comment]
Both the program and `libdeflate` have been compiled with MSVC, albeit `libdeflate` with `2017` instead of `2019`. But I tried compiling my program with the same MSVC version and it still outputs the same results.

**Comment by ebiggers** [comment]
Okay.  One possibility is that MSVC is miscompiling the Adler-32 code.  However, it doesn't reproduce with version 19.34.31933.0 from Visual Studio 2022.  libdeflate's GitHub Actions CI also uses Visual Studio 2022.  I wonder if this problem is specific to older MSVC versions.

**Comment by sumit0190** [comment]
I am sorry, I didn't think to check the binaries provided by you - I instead used the versions provided by `conda`, as those are the ones that led me to finding this behavior. But you are right - with your binaries both versions are able to correctly decompress the data. It almost certainly has something to do with the compiler, I guess we can be sure of that now. I would say we can close this issue, since it'd probably be hard for you to reproduce it unless you can get your hands on the exact compiler version. I can try to rebuild the binaries provided by `conda` with a newer version - hopefully that'll take care of this.

Thanks for all the help!

**Comment by ebiggers** [comment]
https://github.com/ebiggers/libdeflate/pull/309 added Visual Studio 2019 to libdeflate's CI, and no issue is seen.  Though, that doesn't completely exclude an issue with the Adler-32 code with VS2019, since libdeflate has multiple Adler-32 implementations and it chooses one at runtime based on the CPU features.  "Modern" CPUs all use the AVX-2 implementation of Adler-32, though.

Maybe VS2017 is needed to see the issue.  Unfortunately, GitHub Actions doesn't have VS2017, and Microsoft doesn't provide downloads of VS2017 without signing in.  So I can't easily confirm this.

Even if this is a compiler bug, I do consider it my responsibility to work around them...  In this case, assuming my unconfirmed hypothesis is correct, the workaround would probably be to make libdeflate ifdef out the x86 optimized Adler-32 code if the compiler is MSVC and its version is too old.

**Comment by ebiggers** [comment]
(For reference, in theory libdeflate is supposed to support Visual Studio 2015 and later currently...)

**Comment by sumit0190** [comment]
Since I do have access to this specific compiler version (`VS 2017 v15.9.26`) I can help you out here. If there's a patch you want me to apply - including any changes to the code or adding information that could help you debug the issue - let me know and I can try it out.

**Comment by ebiggers** [comment]
Can you check to see if https://github.com/ebiggers/libdeflate/pull/310 would make the problem go away?  Thanks!

**Comment by sumit0190** [comment]
Hmm I don't think that did the trick. Tried it a couple of times on different machines, but saw the same results with my compiler. Maybe we can add some debug statements somewhere to better understand what's going on? I have no idea how feasible that is in low-level code like this though.
