### ISSUE TITLE
Comparison to zlib and its forks

### ISSUE THREAD

**Issue by alejandro-colomar** [ebiggers/libdeflate#315]
Hi Eric!

I'm going to add gzip compression to a web server (<https://unit.nginx.org/>).
My initial candidate is zlib, as it's what was used in NGINX.
I've seen that there are forks of [zlib](https://github.com/madler/zlib) that are faster, like [zlib-cloudflare](https://github.com/cloudflare/zlib), which seems to be the fastest fork today,
but since they should be drop-in compatible, I'd program against the original zlib.

I understand your implementation is only for a single buffer (no streaming), and that makes it unsuitable for some uses in a web server.
However, my idea is that if your implementation is considerably faster, maybe it would be interesting to selectively use it in the cases where the buffer size is known and of an appropriate size.

So, I'd like to ask a few questions:

-  You claim libdeflate is faster than zlib.  Can you specify by how much?
-  Does buffer size affect the performance difference?  Or does libdeflate outperform zlib for all buffer sizes?
-  Is it still faster than Cloudflare's fork of zlib?  By how much?  (I've seen claims that Cloudflare's zlib is ~90% faster for compression and ~50% faster for decompression, compared to the original zlib)
-  How about memory usage?  That's quite important for my use case.  Does it use similar resources?
-  You say for big buffers libdeflate uses huge memory.  Are small buffers safe from that?  At what size should I start worrying?

Thanks!
Alex

**Comment by ebiggers** [comment]
Usually libdeflate is over twice as fast as vanilla zlib, both for compression and decompression.  It's also usually faster than the zlib forks, by a smaller factor.  I don't provide benchmark results myself, for a couple reasons.

First, benchmarking compression algorithms is hard.  It depends on many factors such as the choice of inputs, compression level, CPU, compiler, compiler options, version of the software being benchmarked, whether it's compression or decompression, and choice of format (gzip, zlib, or raw DEFLATE in this case).  It's not something I want to get into with providing "official" numbers.  Users can do benchmarks that measure their actual use case.

Second, I don't really try to "market" libdeflate over competing projects.  libdeflate is a "passion project" where I collect what seem to be the best algorithms for DEFLATE compression and decompression on modern CPUs.  If people want to use it, great, but that's on their own initiative.  So, the only real reason I have to explicitly compare libdeflate to other projects myself is identify areas where libdeflate needs improvement...  Besides that, I'd rather let users speak for themselves.  There are benchmark results from users available if you look around; e.g. see https://github.com/zlib-ng/zlib-ng/issues/1486 for some recent ones.

I would also generally discourage projects from supporting/using multiple implementations of DEFLATE (such as both libdeflate and zlib) simultaneously, for obvious reasons (code maintenance and code size).  But again it is your choice.

If you want, you can also do benchmarks vs. zlib (vanilla or any fork) yourself using the included `benchmark` tool:

```
   ./scripts/benchmark.sh --help
```

As for memory usage, the memory usage *of libdeflate itself* does not depend on the input size and is described by the following table (measured using latest version on x86_64):

| Struct | Size |
| --- | --- |
| decompressor | 11568 bytes |
| compressor, level 1 | 202720 bytes |
| compressor, level 2-9 | 668256 bytes |
| compressor, level 10-12 | 9011712 bytes |

I think the compressor does use more memory than zlib, even below level 10.  This is to improve performance.

Of course, the input and output buffers that the application using libdeflate allocates will be in memory too.

**Comment by alejandro-colomar** [comment]
> Usually libdeflate is over twice as fast as vanilla zlib, both for compression and decompression. It's also usually faster than the zlib forks, by a smaller factor. I don't provide benchmark results myself, for a couple reasons.

Thanks, that's what I wanted to know :)

> 
> First, benchmarking compression algorithms is hard. It depends on many factors such as the choice of inputs, compression level, CPU, compiler, compiler options, version of the software being benchmarked, whether it's compression or decompression, and choice of format (gzip, zlib, or raw DEFLATE in this case). It's not something I want to get into with providing "official" numbers. Users can do benchmarks that measure their actual use case.

Yeah, for specific comparisons, it's better to do my own tests.  I was more interested in a rough estimate of the order of magnitude, i.e., ~1.1x or ~2x or ~10x improvements.

> 
> Second, I don't really try to "market" libdeflate over competing projects. libdeflate is a "passion project" where I collect what seem to be the best algorithms for DEFLATE compression and decompression on modern CPUs. If people want to use it, great, but that's on their own initiative. So, the only real reason I have to explicitly compare libdeflate to other projects myself is identify areas where libdeflate needs improvement... Besides that, I'd rather let users speak for themselves. There are benchmark results from users available if you look around; e.g. see [zlib-ng/zlib-ng#1486](https://github.com/zlib-ng/zlib-ng/issues/1486) for some recent ones.

Thanks, that more or less confirms the order of magnitude being ~2x faster.

> 
> I would also generally discourage projects from supporting/using multiple implementations of DEFLATE (such as both libdeflate and zlib) simultaneously, for obvious reasons (code maintenance and code size). But again it is your choice.

Agree.  If the order of magnitude would have been over 10x, I would have considered it, but 2x isn't worth it, especially since it's smaller compared to zlib forks.

> 
> If you want, you can also do benchmarks vs. zlib (vanilla or any fork) yourself using the included `benchmark` tool:
> 
> ```
>    ./scripts/benchmark.sh --help
> ```
> 
> As for memory usage, the memory usage _of libdeflate itself_ does not depend on the input size and is described by the following table (measured using latest version on x86_64):
> Struct 	Size
> decompressor 	11568 bytes
> compressor, level 1 	202720 bytes
> compressor, level 2-9 	668256 bytes
> compressor, level 10-12 	9011712 bytes
> 
> I think the compressor does use more memory than zlib, even below level 10. This is to improve performance.
> 
> Of course, the input and output buffers that the application using libdeflate allocates will be in memory too.

Thanks this helps! :)
