### ISSUE TITLE
POSITION_INDEPENDENT_CODE ON for static compilations

### ISSUE THREAD

**Issue by sanguinariojoe** [ebiggers/libdeflate#317]
You really want to add that option [here](https://github.com/ebiggers/libdeflate/blob/master/CMakeLists.txt#L186). Otherwise static linking inside dynamic libraries would be impossible (like it is usually the case when making Python wheels)

**Comment by ebiggers** [comment]
You can already set `-DCMAKE_POSITION_INDEPENDENT_CODE=1` when running cmake, if you want to.  Is there a strong reason you want libdeflate to force it on for the static library, overriding the cmake default behavior?

**Comment by sanguinariojoe** [comment]
Hey! Sorry, I missed this reply. Luckily @cary-ilm drawn my attention on this.

That option seems to work just fine.

https://github.com/sanguinariojoe/openexr/actions/runs/5701914625

I actually did not know you can add such an option to CMake... My bad
