### ISSUE TITLE
Please also generate a static source code archive for release

### ISSUE THREAD

**Issue by diizzyy** [ebiggers/libdeflate#328]
Due to https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/ it would appreciated for packaging if there also could be a static source code archive available

**Comment by ebiggers** [comment]
I uploaded a source tarball `libdeflate-1.19.tar.gz`.  I'll include a source tarball in future releases too.

**Comment by diizzyy** [comment]
Thanks! :-)
