### ISSUE TITLE
Slow level 0 "compression"

### ISSUE THREAD

**Issue by dktapps** [ebiggers/libdeflate#333]
Level 0 `libdeflate_deflate_compress` is strangely slow, much slower than zlib.

It spends most of its time in `deflate_compress_lazy_generic`, doing what I have no idea, since it should just be adding a header and a footer as far as I can tell.

Tested with payloads of 250x `NUL` bytes.

**Comment by ebiggers** [comment]
This suggests that you are not actually using level 0.  Please ensure that you are really passing 0 to `libdeflate_alloc_compressor()`.

**Comment by dktapps** [comment]
Sorry, you are correct, I had a bug in my code :)
