### ISSUE TITLE
ESA matchfinder

### ISSUE THREAD

**Issue by andrews05** [ebiggers/libdeflate#336]
I don't know if this is at all relevant, but I came across this and wondered if it could be applied to libdeflate.
https://github.com/IlyaGrebnov/esa-matchfinder

Apparently it's based on some of your own work. It's supposedly faster and more effective than HC/BT algorithms (as used in LZMA).

**Comment by ebiggers** [comment]
I've already tried that, but for libdeflate the HC and BT matchfinders are better because the maximum match offset in DEFLATE is only 32768, and a sliding window needs to be supported.

**Comment by andrews05** [comment]
Thanks for the info! Are you saying ESA is unsuitable for deflate in general?

**Comment by ebiggers** [comment]
Yes, I think so.  It can be used, but it's not the best option.

**Comment by andrews05** [comment]
Sliding window support was actually added in v1.1, does that make difference?
