### ISSUE TITLE
Debian Library Packaging?

### ISSUE THREAD

**Issue by sargun** [ebiggers/libdeflate#34]
Are you okay if someone submits a PR to build a Debian package for this library?

**Comment by ebiggers** [comment]
There's now a Debian package for libdeflate: https://packages.debian.org/source/sid/libdeflate

I'm not the maintainer of it though, so it doesn't really make sense to include Debian packaging files in the libdeflate repository directly.

But I did [commit a change](https://github.com/ebiggers/libdeflate/commit/314641f6a8ad5f5ab9476186f03089f99f138c41) to add a soname to the shared library.  So, the Debian package won't have to add that as an extra patch anymore.
