### ISSUE TITLE
analyzer warning regression: The left operand of '+' is a garbage value due to array index out of bounds

### ISSUE THREAD

**Issue by Coeur** [ebiggers/libdeflate#357]
The Apple clang analyzer is showing this new warning:
>The left operand of '+' is a garbage value due to array index out of bounds

The regression came with a50c51bc9edda5d9e63dda10503570c4f4ac6d01 (#316) apparently
![Capture d’écran 2024-03-18 à 10 39 43](https://github.com/ebiggers/libdeflate/assets/839992/c260efd9-7cc8-47c8-bf29-ad6d28445cb7)
![Capture d’écran 2024-03-18 à 10 40 15](https://github.com/ebiggers/libdeflate/assets/839992/da5e8244-9475-47ba-ab22-76a1a7128695)
![Capture d’écran 2024-03-18 à 10 44 03](https://github.com/ebiggers/libdeflate/assets/839992/0f26e6f4-050b-4045-85b6-ec7577e22c92)
![Capture d’écran 2024-03-18 à 10 40 44](https://github.com/ebiggers/libdeflate/assets/839992/247ae1a1-641e-4545-9312-1f349a4c5a7b)

**Comment by ebiggers** [comment]
It's a false positive.  https://github.com/ebiggers/libdeflate/pull/358 suppresses it by adding an assertion for that function's preconditions.
