### ISSUE TITLE
Building error in ARM v8 system

### ISSUE THREAD

**Issue by casm-ahb** [ebiggers/libdeflate#388]
When I builded the libdeflate v1.21 on Kylin v4 with Feiteng CPU (ARM v8),  errors were reported liking the following:
......
[35%] Building C object CMakeFiles/libdeflate_shared.dir/lib/adler32.c.o
/tmp/cc6o7Zmc.s: Assembler messages:
/tmp/cc6o7Zmc.s 423: error: unknown architectural extension 'dotprod'
/tmp/cc6o7Zmc.s 494: error: unknown mnemonic 'udot' -- 'udot v27.4s,v19.16b,v23.16b'
/tmp/cc6o7Zmc.s 495: error: unknown mnmeonic 'udot' -- 'udot v20.4s,v18.16b,v24.16b'
.....
CMakeFiles/libdeflate_shared.dir/build.make:145: recipe for target 'CMakeFiles/libdeflate_shared.dir/lib/adler32.c.o' failed

How to slove the problem?

**Comment by ebiggers** [comment]
What operating system is this (e.g. Linux distro version), and what gcc and binutils versions are you using?

**Comment by ebiggers** [comment]
Can you check if https://github.com/ebiggers/libdeflate/pull/389 allows libdeflate to build on your system?

**Comment by casm-ahb** [comment]
> What operating system is this (e.g. Linux distro version), and what gcc and binutils versions are you using?

tianyue@tianyue-Kaifaban:~$ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/data/ThirdParty/gcc-10.5.0/Install/libexec/gcc/aarch64-linux-gnu/10.5.0/lto-wrapper
target：aarch64-linux-gnu
configured：../configure --enable-languages=c,c++ --enable-threads=posix --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu --prefix=/data/ThirdParty/gcc-10.5.0/Install
thread model：posix
Supported LTO compression algorithms: zlib
gcc version 10.5.0 (GCC)

**Comment by ebiggers** [comment]
https://github.com/ebiggers/libdeflate/pull/389 should work around this, though it is better to upgrade your binutils to match your gcc version.
