### ISSUE TITLE
libdeflate_deflate_decompress return  error of 'LIBDEFLATE_BAD_DATA = 1'

### ISSUE THREAD

**Issue by guoxiaolongzte** [ebiggers/libdeflate#393]
auto res = libdeflate_deflate_decompress(decompressor, inputPtr, length, output, maxOutputLength, &actual);
        if (res != LIBDEFLATE_SUCCESS) {
            const char* version = LIBDEFLATE_VERSION_STRING;
            LOG(WARNING) << "libdeflate_deflate_decompress return res: " << res;
            LOG(WARNING) << "Decompression outcomes include: "
                            "LIBDEFLATE_SUCCESS = 0 (decompression was successful), "
                            "LIBDEFLATE_BAD_DATA = 1 (decompression failed due to invalid, corrupt, or unsupported compressed data), "
                            "LIBDEFLATE_SHORT_OUTPUT = 2 (a NULL 'actual_out_nbytes_ret' was provided when the decompressed data "
                            "would be less than 'out_nbytes_avail' bytes), and "
                            "LIBDEFLATE_INSUFFICIENT_SPACE = 3 (the decompressed data would exceed 'out_nbytes_avail' bytes).";
            throw ParseError("LibDefalte decompress failed");
        }

version:1.21     return res=1 LIBDEFLATE_BAD_DATA = 1 (decompression failed due to invalid, corrupt, or unsupported compressed data)，why？

**Comment by ebiggers** [comment]
Well, it is as the error code describes.

I don't know what values you were passing into the function, so I can't help further.
