### ISSUE TITLE
Deterministic compression

### ISSUE THREAD

**Issue by Pique7** [ebiggers/libdeflate#400]
Is it possible to define compression settings which guarantee a deterministic output (always the same byte sequence)?
I don't want to compress whole files but only chunks of data.

**Comment by ebiggers** [comment]
The current implementation is deterministic for a particular version of libdeflate.  This should not be relied on, because it only applies to a particular version of libdeflate, and the output can change the next time you upgrade libdeflate.

I will not guarantee the same compressed output across different versions of libdeflate, because that would prevent making improvements to the algorithms.

**Comment by Pique7** [comment]
Thanks for the acceptably concrete answer - even though I was hoping there was a way to achieve it.

**Comment by Bulat-Ziganshin** [comment]
> Thanks for the acceptably concrete answer - even though I was hoping there was a way to achieve it.

can you include/link the fixed libdefalte version?

**Comment by ebiggers** [comment]
No version of libdeflate has ever been non-deterministic, but the output has varied across versions and will continue to vary across versions in the future.  There is nothing to "fix".

**Comment by Bulat-Ziganshin** [comment]
yeah, I mean that the topic starter can use the same libdeflate version forever and thus solve his problem

**Comment by ebiggers** [comment]
Sure.  I strongly recommend not doing that.  Instead, design the application to not depend on the compressed outputs remaining the same forever.  For example, if doing data deduplication, then deduplicate by the uncompressed data instead of by the compressed data.

**Comment by cieplutki** [comment]
> Is it possible to define compression settings which guarantee a deterministic output (always the same byte sequence)?

AFAIC that's not indetereministic as it would imply randomness, which is not the case, as it would invalidate it as a compressor.
It's non-bijective; non-surjective either.

Apart form mathematical nomeclature LZSS, like deflate, can output two, or more, perfectly valid outputs for the same input.
