### ISSUE TITLE
Heisenbug in crc code when 512-bit vectors are used with Intel C++ compiler

### ISSUE THREAD

**Issue by pps83** [ebiggers/libdeflate#403]
I installed recently Intel's c++ compiler (I have 2024, and 2025 version). I didn't check my unit tests with intel compiler, but recently I noticed that one test fails *sometimes*. This my unit test simply calculates crc32 using zlib-ng and using libdeflate and reports timings. The crazy part is that the bug sometimes disappears: the same binary executed multiple times and sometimes libdeflate fails and sometimes returns correct crc32 value. When it fails, it always returns the same value (eg it's not always different when it fails).

Curious observation is that the build sometimes fails only when running non-optimized version. Just while writing this message I double checked different combinations and it appears that clang-cl also has the same issue!
These are the only differences that I have from public libdeflate: https://github.com/ebiggers/libdeflate/compare/master...pps83:libdeflate:master

**Comment by pps83** [comment]
Here's minimal repro test: https://github.com/pps83/libdeflate/tree/crctest (you need to build with clang-cl for Debug x64).
That's the output I get *sometimes*:
```
crc32:3403043317
ERROR: libdeflate crc32:2268885453
```

**Comment by ebiggers** [comment]
Thanks.  https://github.com/ebiggers/libdeflate/pull/404 should fix this.

**Comment by pps83** [comment]
> Thanks. #404 should fix this.

that was quick. I'll test and report.

**Comment by pps83** [comment]
fix works. FYI, added a comment here: https://github.com/ebiggers/libdeflate/pull/341#issuecomment-2504605912

**Comment by ebiggers** [comment]
> I'm wondering why is that msvc build doesn't have that issue

Well, it is quite difficult for compilers to generate code that does *not* zeroize the upper bits when extending 128 bits to 512 bits, considering how the underlying instruction set works.  clang somehow managed to do so, but only at `-O0` where the generated code is very unoptimized and messy.
