### ISSUE TITLE
Installation with --prefix

### ISSUE THREAD

**Issue by serge2016** [ebiggers/libdeflate#46]
Hello!

Could you tell me, please, how to install `libdeflate` in a custom directory in the similar way as it is usually possible with `./configure --prefix "/my/custom/path"`?
And what environmental variable I should export in this case?

**Comment by ebiggers** [comment]
It's `make install PREFIX=/my/custom/path`.

I updated the README and the comment in the Makefile to make this easier to find.

**Comment by serge2016** [comment]
Dear @ebiggers, thank you!
And what environmental variable I should export in the case when I change `PREFIX`?

**Comment by ebiggers** [comment]
`PREFIX=/my/custom/path make install` will work too.  But if you have a choice, prefer to set it via the first method (as a make variable, not an environmental variable).

**Comment by serge2016** [comment]
@ebiggers my question is about those environmental variables, that I should set after the installation for other tools could get this library, e.g. `htslib`... I am a newbie in the compilation and variable like `LD_PATH` or others...

**Comment by ebiggers** [comment]
If you install a library (e.g. libdeflate) into `$prefix`, then when compiling something using the library you need to set `CPPFLAGS=-I$prefix/include` and `LDFLAGS=-L$prefix/lib`.  And to run binaries, you need to export `LD_LIBRARY_PATH=$prefix/lib`.

None of this is specific to libdeflate.

**Comment by serge2016** [comment]
@ebiggers, thank you very much!
