### ISSUE TITLE
mkdir -p $LIBDIR $INCDIR

### ISSUE THREAD

**Issue by serge2016** [ebiggers/libdeflate#47]
Dear @ebiggers, I am trying to use https://github.com/ebiggers/libdeflate/issues/46#issuecomment-507921500, but I get 2 errors:
```
install -Dm644 -t /soft/2/libdeflate-190703/lib libdeflate.a
install: failed to access '/soft/2/libdeflate-190703/lib': No such file or directory
make: *** [install] Error 1
```
and the same about `include`. It is because both `lib` and `include` directories do not exist and are not automatically created (`bin` is created automatically). 
I suggest to add `mkdir -p ...` for both these directories:
https://github.com/ebiggers/libdeflate/blob/debaabad373440dbbc9bdfc81d5a868f27d332e6/Makefile#L265

**Comment by ebiggers** [comment]
`install` should automatically create the directories since the `-D` option is specified.  It works for me.  What operating system are you using?

**Comment by serge2016** [comment]
I use `ubuntu:14.04`.

**Comment by ebiggers** [comment]
Okay, looking at the source code history of `install` in coreutils, apparently `-t` and `-D` only work correctly in combination in coreutils v8.23 and later.

I'll make the changes you're suggesting, though the current code is not really "wrong", it just runs into a bug in 5+ year old coreutils.

**Comment by serge2016** [comment]
Thank you! Now it works!
