### ISSUE TITLE
How can I build libdeflate on windows10 using MinGW and make

### ISSUE THREAD

**Issue by bolunfeng** [ebiggers/libdeflate#48]
How can I build libdeflate on windows10 using MinGW and make?

**Comment by bolunfeng** [comment]
D:\software\gt_compress\3thparty\libdeflate>make --version 
GNU Make 4.0.90
Built for Windows32
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

D:\software\gt_compress\3thparty\libdeflate>gcc --version 
gcc (i686-win32-dwarf-rev3, Built by MinGW-W64 project) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


D:\software\gt_compress\3thparty\libdeflate>make CC=gcc
此时不应有 -Wpedantic。
此时不应有 -Wdeclaration-after-statement。
此时不应有 -Wmissing-prototypes。
此时不应有 -Wstrict-prototypes。
此时不应有 -Wvla。
系统找不到指定的路径。
'flags' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Makefile:156: recipe for target '.lib-cflags' failed
make: *** [.lib-cflags] Error 1

**Comment by ebiggers** [comment]
Use the directions in the README file: https://github.com/ebiggers/libdeflate#for-windows

**Comment by bolunfeng** [comment]
Using Cygwin:

fengbolun@fengbolun-PC ~/libdeflate
$ make BUILD_GZIP_PROGRAM=yes
  CC       programs/gzip.o
In file included from /usr/include/errno.h:9:0,
                 from programs/gzip.c:30:
/usr/include/sys/errno.h:25:23: 错误：与‘program_invocation_name’类型冲突
 extern __IMPORT char *program_invocation_name;
                       ^~~~~~~~~~~~~~~~~~~~~~~
In file included from programs/gzip.c:28:0:
programs/prog_util.h:117:21: 附注：‘program_invocation_name’的上一个声明在此
 extern const tchar *program_invocation_name;
                     ^~~~~~~~~~~~~~~~~~~~~~~
programs/gzip.c: 在函数‘main’中:
programs/gzip.c:531:26: 警告：assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  program_invocation_name = get_filename(argv[0]);
                          ^
make: *** [Makefile:226：programs/gzip.o] 错误 1

**Comment by ebiggers** [comment]
Please follow the directions.  That's not the correct `make` command.

**Comment by bolunfeng** [comment]
ok.thanks.

**Comment by bolunfeng** [comment]
I still have a question, how can I install the generated library files into the specified directory through your command?

**Comment by ebiggers** [comment]
You just have to copy the wanted files somewhere yourself, if needed.  There is `make install`, but it assumes a UNIX directory structure.  For Windows builds, there's no standard; everyone will want something different.
