### ISSUE TITLE
test failure on ppc64el

### ISSUE THREAD

**Issue by mr-c** [ebiggers/libdeflate#53]
On a recent build of the libdeflate 1.3 Debian package 

```
SMOKEDATA=/<<PKGBUILDDIR>>/README.md WRAPPER= sh tools/exec_tests.sh
 ./test_checksums
 ./test_incomplete_codes
 ./test_slow_decompression
test_slow_decompression: Assertion failed: t < tz at programs/test_slow_decompression.c:446
Aborted
```

We've never run these particular tests before, so I don't know if this wasn't working in prior versions.

Full log is at https://buildd.debian.org/status/fetch.php?pkg=libdeflate&arch=ppc64el&ver=1.3-1&stamp=1566583337&file=log

**Comment by ebiggers** [comment]
This a performance test, so it's flaky.  I've gone ahead and disabled it by default in  0015560a826e0fde278480b5594fa7d452d1a9cd ("test_slow_decompression: skip by default since it's flaky").  Thanks!  Also, you might want to consider using the new `make check` target.
