### ISSUE TITLE
Could you compile a second version with StdCall?

### ISSUE THREAD

**Issue by Videogamer555** [ebiggers/libdeflate#58]
I know you use Cdecl as the calling convention now, but could you also add a second parallel branch to your project, with StdCall? I need the functionality of libdeflate, without the burden of writing using C as my programming language. I use VB6 (yes it's old, but it works fine for 99% of what I do) and VB6 requires StdCall. Unlike in C, in VB6 there's no option of importing a DLL function that uses the Cdecl calling convention. It's either StdCall, or the function CAN'T be called. The ONLY time I use C or C++ is when I want to write code better optimized for speed, but at the expense of it being much more difficult to write the program. For everything else I use VB6. With C++ you can't just create a window and add buttons. You need to spend days of coding just to create the window, add buttons, and program it to even be able to respond to button clicking (this means detecting and responding to window messages). In VB6, the ONLY code you need to write that tells it what to do when a button is clicked. The actual act of detecting a button click is part of the code that is automatically generated by VB6 itself, as is code that corresponds to creating and displaying the window and adding and displaying buttons on that window. You literally just drag-drop buttons (and other controls) onto the window, and internally VB6 generates all the code that is needed to handle these controls.

So please don't ask me to migrate to C or C++ for my programming needs. That's not going to happen. I need you instead compile a separate branch of libdeflate, which is the same as the main branch in every way but one, and that one way is that the functions must be StdCall functions instead of Cdecl functions.

**Comment by ebiggers** [comment]
FWIW, lots of programming languages support calling functions that use the cdecl calling convention, not just C and C++.  Normally there is a way to choose which calling convention is used.

It sounds like VB6 is an exception though.

I'm thinking it would be better to just provide one build, which uses stdcall.  It's what the Windows API uses, so presumably everyone supports it.

Also just checking: you do actually need the 32-bit support, right?  If you use the 64-bit binary this is not an issue at all.

**Comment by Videogamer555** [comment]
Yes. Just need 32bit support. I don't need 64bit version, as VB6 only compiles 32bit code.

**Comment by ebiggers** [comment]
I've changed the calling convention to stdcall.  Can you please try https://github.com/ebiggers/libdeflate/releases/download/v1.4/libdeflate-1.4-windows-i686-bin.zip?
