### ISSUE TITLE
Your StdCall function names have weird suffix, and VB6 doesn't like it.

### ISSUE THREAD

**Issue by Videogamer555** [ebiggers/libdeflate#59]
Thanks for putting StdCall functions in the 32bit Windows version. However this has its own problem now. The functions now contain a suffix in the name of the function itself. For example, the function libdeflate_crc32 is now called libdeflate_crc32@12. Is there some way for you to tell your compiler to not add these numbers and @ symbols at the end of the function names? The @ symbol makes a problem for VB6, which is the programming language I'm using. VB6 does not allow an functions to contain the @ symbol in the function name. All of the Windows API functions that work in VB6 are StdCall functions, but none of the Windows API functions contain a suffix like this. They don't have an @ symbol followed by a number. One example is the Windows API function VirtualAlloc in kernel32.dll which is used to allocate a block of virtual memory. It's not something like VirtualAlloc@12. It's just plain VirtualAlloc.

**Comment by ebiggers** [comment]
Thanks for pointing this out; I didn't know that (for some reason) there are two incompatible naming conventions for stdcall, and that the default behavior of both MinGW and MSVC is to use the naming convention that's incompatible with the Win32 API.  I've added the `--add-stdcall-alias` flag for the MinGW linker, so the DLL should support both naming conventions now.  Can you try https://github.com/ebiggers/libdeflate/releases/download/v1.5-beta1/libdeflate-1.5-beta1-windows-i686-bin.zip?

**Comment by Videogamer555** [comment]
Yep. It works now. Thanks.
