### ISSUE TITLE
Add portable fallback for unknown platforms

### ISSUE THREAD

**Issue by nemequ** [ebiggers/libdeflate#6]
https://graphics.stanford.edu/~seander/bithacks.html has some portable implementations of several of the compiler-specific functions; see the "Finding integer log base 2 of an integer (aka the position of the highest bit set)" and "Counting consecutive trailing zero bits (or finding bit indices)" sections.

**Comment by ebiggers** [comment]
I don't think anything else needs to be done here.  There are some builtins and instrinsics used, but only when believed to be supported by the compiler.  There is a generic compiler.h header which includes a header for the specific compiler (currently, gcc-like or MSVC).  The library can be built without including a compiler-specific header at all, although for performance reasons this isn't recommended.

If you come across a specific problem then please feel free to file a new issue.

**Comment by nemequ** [comment]
compiler.h doesn't look very complete; are all calls to (for example) `compiler_fls32` protected with an ifdef?  I would expect to see a portable version there, and have the macro called unconditionally…

**Comment by ebiggers** [comment]
The portable version of that is in `bitops.h`.  You call `fls32()`, not `compiler_fls32()` directly.  `bitops.h` maybe should be merged into `compiler.h`, but for now it is separate.
