### ISSUE TITLE
Z_SYNC_FLUSH equivalent

### ISSUE THREAD

**Issue by MartenF** [ebiggers/libdeflate#61]
Does libdeflate have some kind of equivalent to zlibs Z_SYNC_FLUSH?
For my application i need to compress a single packet of data completely, send it of, and then compress the next packet without resetting the compressor.

Does libdeflate_deflate_compress allways flush all the input data (if enough output space is available) or does is delay bits.

**Comment by ebiggers** [comment]
I assume you figured it out by now, but libdeflate currently only supports compressing a whole buffer at a time, into a complete DEFLATE / zlib / gzip stream.  The compression state is reset each time.  Sorry for not responding to this question earlier.
