### ISSUE TITLE
ZLIB bad data

### ISSUE THREAD

**Issue by t0rakka** [ebiggers/libdeflate#64]
I have a few png files which yield ZLIB bad data error when trying to decompress the IDAT chunks; the data decompresses OK with latest (and older versions) of zlib.

I stashed the files here:
http://www.liimatta.org/misc/png_baddata/

**Comment by t0rakka** [comment]
I dumped the IDAT chunks for the kde4.png  into a file kde4.idat, it's just a binary blob which should be zlib decompressible and can be used to expose the ZLIB BAD DATA error.

**Comment by ebiggers** [comment]
I don't understand, what is the issue here?  I tried decompressing your `kde4.idat` file (699160 bytes with md5sum c0a1bd50a40a1f05b5e2c07cb52a01c2) with both libdeflate and libz, and both work fine -- they both produce 5184900 bytes with md5sum 35188310c5e9cc2f1f3f8f70d3574212.

Are you saying you got the error `LIBDEFLATE_BAD_DATA`?  Can you check how you're invoking `libdeflate_zlib_decompress()`?

**Comment by t0rakka** [comment]
Oh wow, it seems to be a bug in GCC-10! Fails with this compiler on Linux Mint 19.3:

g++ (Ubuntu 10-20200416-0ubuntu1~18.04) 10.0.1 20200416 (experimental) [master revision 3c3f12e2a76:dcee354ce56:44b326839d864fc10c459916abcc97f35a9ac3de]

^ experimental.. doh!

Works fine on macOS command line clang:

Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.3.0

I'll check what happens with older GCC.. probably works.. a minute...

**Comment by t0rakka** [comment]
Yup. GCC 9.3.0: works A-OK. Sorry for the false alarm; close the issue with confidence! 

Everything else has worked and passed regressions pretty nicely, this was the first flag I got.. is it may be possible that there may be some UB lurking which the latest code-generator exposed? Not saying it's so, probably just pains with the new compiler but something to look out for.. thanks for the patience. :)

**Comment by t0rakka** [comment]
Did a bit of digging, looking for the usual suspects like unions and type punning.. the culprit is 

#  define UNALIGNED_ACCESS_IS_FAST 1

.. seems the packed struct approach breaks on gcc-10. The memcpy fallback generates top-notch code so I'm fine with that for now. Cheers, great library,  btw.. love the sick speed, keep up the good work! :)

**Comment by t0rakka** [comment]
I got a few other local patches as well, but nothing I'm too keen on pushing your way. Just leaving a note. crc32.c, adler32.c and utils.c are so generic names that other libraries use same translation unit names, so getting some linker warnings about duplicate symbols. Renamed here to libd_crc32.c and so on.. the cpu_features.c conflict with each other, so I have them named as cpu_arm_features.c and cpu_x86_features.c, no big deal.. just extra steps when merging.

xcode gives a couple of warnings about losing precision from "long" to "s32/u32/unsigned int" in a couple of places.. I just disabled them from the project settings, heh. Last a small thing, it might be better to include some local headers as "../common/common_defs.h"  vs. "common_defs.h" so that don't need the -D for no other reason when building. I integrated this into XCode and Visual Studio solutions so it was extra step which could be avoided.

That's about all that I can think of.. no actions required, I am all set up but these would make some future users life slightly easier. I already did the tricks so for me there wouldn't be any effect on these small quality-of-life improvements. ;-)

**Comment by ebiggers** [comment]
I can reproduce this with gcc built from commit 44b326839d8, when using `-O3` (not when using `-O2`).  The part that's being miscompiled is the word-at-a-time copy loop in `decompress_template.h`:

                                do {
                                        copy_word_unaligned(src, dst);
                                        src += WORDBYTES;
                                        dst += WORDBYTES;
                                } while (dst < out_next);

`copy_word_unaligned()` uses those `packed` structures generated by `DEFINE_UNALIGNED_TYPE()`.

I don't believe there's any undefined behavior here.  To be safe I'm considering adding `may_alias` to the `packed` structs, but it makes no difference here.

When I have a chance, I'll retry with latest gcc master (which is 12 days newer), and if it still reproduces, I'll try to figure out what's going on.

**Comment by ebiggers** [comment]
> crc32.c, adler32.c and utils.c are so generic names that other libraries use same translation unit names, so getting some linker warnings about duplicate symbols.

I don't understand why the name of the files matters here?  All libdeflate's global symbols are prefixed with libdeflate, so you shouldn't get any symbol collisions.

> Renamed here to libd_crc32.c and so on.. the cpu_features.c conflict with each other, so I have them named as cpu_arm_features.c and cpu_x86_features.c, no big deal.. just extra steps when merging.

Likewise, I don't understand the problem with `cpu_features.c`.  You are supposed to compile all of them; the ones not for your architecture just get automatically `#ifdef`'ed out.  And the files are in different directories, so why would the duplicate filenames matter?

> xcode gives a couple of warnings about losing precision from "long" to "s32/u32/unsigned int" in a couple of places.. I just disabled them from the project settings, heh.

gcc `-Wconversion` generates several hundred warnings... I don't think it would improve the code at all to add explicit casts to silence these.  Just don't enable this warning.

> Last a small thing, it might be better to include some local headers as "../common/common_defs.h" vs. "common_defs.h" so that don't need the -D for no other reason when building.

That might make sense.

**Comment by t0rakka** [comment]
The files are not in different directories in Visual Studio, but don't worry about it; the VS is a bit retarded sometime. ;)   The -Wconversion is default on XCode but as said, took care of it. These are really minor things that first-timers using these tools might run across.

The cpu_features.c thing was an artefact of creating sln file from cmake build script, which didn't select which one(s) are built based on target arch.. since it's valid to build both the way the code is structured, that caused both to be pulled into the vs build and the linker didn't like it. I use the same arrangement in my codings; it's OK to build the while source tree w/o any discrimination or special casing. That's the way I prefer it anyway, so it's all good, except the dumb thing vs does with builds.. all .obj files are IN THE SAME FOLDER! :_(

Anyway: all is good, just gave some experience-feedback from the field.. as said, everything working smoothly.

**Comment by ebiggers** [comment]
gcc 10.1 still miscompiles libdeflate's word-at-a-time copy loop.  I'm going to switch to `memcpy()` to fix it, since recent gcc's optimize that just as well.  But in case this is a real compiler bug, I'm also checking with the gcc folks at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94994.
