### ISSUE TITLE
List of Wrappers in ReadMe

### ISSUE THREAD

**Issue by 4kills** [ebiggers/libdeflate#70]
Hey @ebiggers, 
first of all: I really appreciate your work with this amazing library that immensely speeds up (de)compression compared to standard zlib.

I've seen that some people on Github have created wrappers for this library for other programming languages (like these Rust bindings: https://github.com/adamkewley/libdeflater). 
I wonder what you think about the suggestion to make a section in the ReadMe linking to such wrappers (like facebook has it with their zstd) in order to make it easier for people to use this great library with their language of choice! 

To give my two cents: I've looked for a Go wrapper of this library (and maybe one exists already) but haven't found any, so I created one myself: https://github.com/4kills/go-libdeflate. 

Edit: fixed link

**Comment by IzumiRaine** [comment]
Hi,

just to clarify, the original repository for the Rust bindings is this one: https://github.com/adamkewley/libdeflater

**Comment by 4kills** [comment]
Hi,
sorry, I didn't notice it was a fork (how stupid of me) as I stumbled over it. I changed the link in the original post.

**Comment by astei** [comment]
Throwing my hat in the ring. Here's my Java bindings: https://github.com/astei/libdeflate-java

**Comment by ebiggers** [comment]
https://github.com/ebiggers/libdeflate/pull/81/commits/ebcb8f10048638333686777f2f035a30116d84e3 added links to Go, Java, Julia, Ruby, and Rust bindings.
