### ISSUE TITLE
Rename gzip application to deflate.

### ISSUE THREAD

**Issue by rhpvorderman** [ebiggers/libdeflate#71]
Dear ebiggers,

Thank you for your great work on redeeming the deflate algorithm and making a fast implementation. I have seen your work implemented as a library and seen its very impressive effects on speed.

Unfortunately, while I can install libdeflate via conda or via the debian package repo I cannot seem to find a command line application that implements libdeflate. Coming here at the source, I see that such a command line application is available, but unfortunately it is named `gzip`. The gzip application in libdeflate also does not support all the flag of the original gzip application and therefore has the potential to break scripts.

Most package maintainers are unwilling to create a package that overwrites the default gzip application with something that is not gzip. 

Some other alternatives exist for gzip:
- pigz (with -p 1) is faster on a single thread than gzip.
- igzip (from [intel's isa-l](https://github.com/intel/isa-l)).

Note how these *are not called gzip* and are therefore easy to install and use alongside venerable gzip. 

I think a renaming would alleviate this problem and allow libdeflate to be used  much more often in everyday command line use.

I suggest using the name `deflate`. The name tells what it does, it stands out from gzip, and emphasises the connection to libdeflate. Also I was not able to find other applications that are already called deflate.

**Comment by ebiggers** [comment]
It's already installed as `libdeflate-gzip` (and `libdeflate-gunzip`) if you run `make install`.

**Comment by rhpvorderman** [comment]
Whoops, sorry!
I just saw it when reading the Makefile.

The suggestion to rename it to `deflate` still stands. It is shorter than `libdeflate-gzip` and has a nice ring to it. "Deflate, a gzip-compatible compression program".

Anyway, thanks again for your work on this project!

**Comment by ebiggers** [comment]
Calling the gzip-like program `deflate` (and presumably `inflate` for the gunzip equivalent?) could be confusing since the program uses the gzip format, not the DEFLATE format.  See https://github.com/ebiggers/libdeflate#deflate-vs-zlib-vs-gzip for what the difference is.  I think it's best to just keep it as `libdeflate-gzip` and `libdeflate-gunzip`.

**Comment by rhpvorderman** [comment]
Thank you for your clear answer. This issue was mainly posted because libdeflate-gzip and libdeflate-gunzip binaries where not provided by distro and conda maintainers. For conda it seemed this was due to naming of the program 'gzip.c'.

I have made a PR for the conda package. The `libdeflate-tools` package is already in debian testing and includes libdeflate-gzip and libdeflate-gunzip.
