### ISSUE TITLE
libdeflate-gzip using lots of memory.

### ISSUE THREAD

**Issue by rhpvorderman** [ebiggers/libdeflate#73]
I did some benchmarking on a 1.6 GiB file in order to check the performance of different deflate tools:

The memory usages were as follows when compressing the file:
- gzip 1.5M
- pigz (one thread) 2.4M
- igzip 3.5M
- libdeflate-gzip 1.6G 

When decompressing the resulting file
- gzip 744K
- pigz (one-thread) 1.2M
- zstd (from .gz) 2.2M
- igzip 3.6M
- libdeflate-gzip 2.2G

This is quite a big difference between the different applications and libdeflate-gzip. It uses 3 orders of magnitude more memory than the others. 
This was using version 1.6.

**Comment by jibsen** [comment]
From the README:

> There is currently no support for streaming. This has been considered, but it always significantly increases complexity and slows down fast paths. Unfortunately, at this point it remains a future TODO. So: if your application compresses data in "chunks", say, less than 1 MB in size, then libdeflate is a great choice for you; that's what it's designed to do. This is perfect for certain use cases such as transparent filesystem compression. But if your application compresses large files as a single compressed stream, similarly to the gzip program, then libdeflate isn't for you.

**Comment by ebiggers** [comment]
Yes, this is working as intended.  To avoid lots of extra complexity and to keep the project manageable for me, libdeflate doesn't aim to support streaming.  If you need to compress 1.6 GiB files into `.gz` format, `libdeflate-gzip` isn't the right tool to use.

**Comment by rhpvorderman** [comment]
Thank you for your clear answers. I apologize for not RTFM.
