### ISSUE TITLE
Compress PNG

### ISSUE THREAD

**Issue by lorents17** [ebiggers/libdeflate#8]
hi!
Tell me, whether it is possible to expect support of compression of PNG?

**Comment by ebiggers** [comment]
PNG is one of many file formats that incorporate DEFLATE, zlib, or gzip streams.  Providing direct support for such file formats is not in scope for this project.  Instead, other projects may use libdeflate to support such file formats.

**Comment by lorents17** [comment]
I wanted to appeal to you. Please, create the application for compression of PNG on the basis of libdeflate, without optimization of filters and other parameters, only compression. for example, [advdef](http://www.advancemame.it/doc-advdef). 
I Am sure, this application will interest many.

For testing ([krzydefc](http://virtual.4my.eu/KrzYdefC/)):

```
for %%i in (PNG\*) do (
	krzydefc --gzipname "%%i"
	7za x "%%i.gz"
	gzip -12 "%%~dpni"
	krzydefc --png"%%~i" "%%~dpni.gz"
	del "%%i.gz"
	del "%%~dpni.gz"
	move /y "%%~dpni.gz.png"  "%%i"
)
```
