### ISSUE TITLE
Maximum compression

### ISSUE THREAD

**Issue by lorents17** [ebiggers/libdeflate#9]
HI!
Tell me, how it is possible to increase extent of compression?

```
$ time /c/Users/Lorents/Desktop/gzip.exe -12 /c/Users/Lorents/Desktop/enwik8

Archive size: 35 215 350 bytes (34 MiB)

real    0m17.382s
user    0m0.000s
sys     0m0.000s
```

```
$ time '/c/Program Files/7-Zip/7z.exe' a -tgzip -mx=9 -mfb=258 -mpass=1 /c/Users/Lorents/Desktop/enwik8.gz /c/Users/Lorents/Desktop/enwik8

7-Zip [64] 16.00 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-10

Archive size: 35 144 526 bytes (34 MiB)

real    0m17.613s
user    0m0.000s
sys     0m0.000s
```

**Comment by ebiggers** [comment]
The main problem with that file is that libdeflate creates too many blocks and wastes too much space sending Huffman codes.  Case in point: if you increase OPTIM_BLOCK_LENGTH in deflate_compress.c from 16384 to 65536 and recompile, then libdeflate gzip -12 compresses enwiki8 to 35,056,842 bytes, beating 7-Zip -mx9.

I am aware that there is work needed to improve the block splitting, especially at high compression modes.  Currently I have spent the most effort optimizing the decompressor and the compressor at low to medium compression modes, which is where libdeflate is primarily intended to compete.  It should also be understood that if you want the "optimum" gzip compression ratio you should probably use Zopfli, which was specifically designed for that purpose.

**Comment by ebiggers** [comment]
libdeflate v0.2 gzip -12 compresses enwiki8 to 35,100,553 bytes.
